- src/components/StripeProvider.tsx
> fix: handle different pjson output

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
> fix: createPaymentMethod promise reject

- README.md
hopefully reverting this PR soon 😄
> fix: update readme; Expo Go not supported yet

- android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkCardView.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/src/screens/NoWebhookPaymentScreen.tsx
- ios/CardFieldView.swift
- ios/PaymentMethodFactory.swift
- ios/StripeSdk.swift
> fix: clear card params when are not valid

- android/src/main/java/com/reactnativestripesdk/StripeSdkCardView.kt
- ios/CardFieldView.swift
- src/components/CardField.tsx
- src/types/components/CardFieldInput.ts
resolves #103 
this feature allows to set ios & android system font families to the CardField component
> add fontFamily prop to CardField 

- example/src/screens/ApplePayScreen.tsx
- ios/ApplePayButtonManager.m
- ios/ApplePayButtonView.swift
- src/components/ApplePayButton.tsx
- src/types/components/ApplePayButtonComponent.ts
> feat: add borderRadius prop to ApplePayButton component

- ios/StripeContainerView.swift
Replaced `setLiestener` for `setListener`
> Fix addListener typo

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
> fix(android): duplicate init configuration

- README.md
> Update Expo note in Readme

- example/src/screens/ApplePayScreen.tsx
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/useStripe.tsx
- src/types/index.ts
> feat(ios): apple pay return paymentMethod

- src/components/ApplePayButton.tsx
- src/components/AuBECSDebitForm.tsx
- src/components/CardField.tsx
- src/components/StripeContainer.tsx
> chore: add testID

- android/src/main/java/com/reactnativestripesdk/CardChangedEvent.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkCardView.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkCardViewManager.kt
- ios/CardFieldManager.m
- ios/CardFieldView.swift
- src/components/CardField.tsx
- src/types/components/CardFieldInput.ts
> feat: dangerouslyGetFullCardDetails

- android/src/main/java/com/reactnativestripesdk/Errors.kt
- android/src/main/java/com/reactnativestripesdk/Mappers.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- ios/Errors.swift
- ios/StripeSdk.m
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/useStripe.tsx
- src/types/Errors.ts
- src/types/index.ts
> feat: retrieveSetupIntent

- android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt
> fix: add missing setupFutureUsage param

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- src/NativeStripeSdk.tsx
- src/functions.ts
> fix: createToken response discrepancy

- android/src/main/java/com/reactnativestripesdk/Constants.kt
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
> WIP:  resolving payment sheet initialization in proper time

- android/src/main/java/com/reactnativestripesdk/Mappers.kt
- ios/Mappers.swift
> fix: dates discrepancies 

- CHANGELOG.md
- README.md
> chore: update expo install instructions in README

- example/src/screens/ApplePayScreen.tsx
- ios/StripeSdk.swift
- src/types/ApplePay.ts
> add JCB support for apple pay

- android/build.gradle
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/Mappers.kt
- android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- e2e/payments.test.ts
- e2e/screenObject/HomeScreen.ts
- example/.env.example
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle.properties
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/StripeSdkExample/Info.plist
- example/package.json
- example/server/index.ts
- example/src/App.tsx
- example/src/components/PaymentScreen.tsx
- example/src/screens/HomeScreen.tsx
- example/src/screens/WeChatPaymentScreen.tsx
- example/yarn.lock
- ios/Mappers.swift
- ios/PaymentMethodFactory.swift
- ios/StripeSdk.swift
- src/types/PaymentMethods.ts
- stripe-react-native.podspec
iOS and Android bindings implementation for WeChat Pay
closes #52
> WIP: Wechat Pay

- src/hooks/useGooglePay.tsx
> fix: google pay type import

- docs/tipsi-stripe-migration-guide.md
> chore: tipsi migration guide

- src/hooks/useStripe.tsx
> isApplePaySupported - null as a default value 

- android/src/main/java/com/reactnativestripesdk/StripeSdkCardView.kt
> fix: card field validation

- example/ios/Podfile.lock
Update Podfile.lock stripe-react-native version on example app.
> fix: update Podfile.lock stripe-react-native version

- example/server/index.ts
Fixes
- Error: Can't set headers after they are sent to the client
- typescripts errors
Refactor
- remove unnecessary async keyword
Checklist
> Bug fixes for server example 

- CHANGELOG.md
> [skip actions] chore: update change log for v0.2.4

- CHANGELOG.md
> [skip actions] update changelog

- CHANGELOG.md
Updated changelog for v0.4.0
release
> [skip actions] updated changelog for v0.4.0

- docs/GooglePay.md
the demo code was using old package
Select one:
> updated typo in package name for example code

- CHANGELOG.md
- android/build.gradle
- example/ios/Podfile.lock
- stripe-react-native.podspec
self-explanatory :) 
CI 
Select one:
> chore: Upgrade underlying native stripe libraries

- CHANGELOG.md
> [skip actions] updated changelog for v0.5.0

- CHANGELOG.md
> [skip actions] Release 0.6.0

- CHANGELOG.md
> Update changelog for v0.8.0 release

- README.md
Update link to running the example app
Improve discoverability.
(n/a)
Select one:
> [docs fix] Update link to running the example app

- CHANGELOG.md
- android/build.gradle
- android/gradle.properties
- example/android/app/build.gradle
Upgraded stripe-android from 20.1.+ to 20.3.+ 
to get bug fixes and features
Select one:
> chore: Upgrade stripe-android to 20.3.+

- CHANGELOG.md
> [skip actions] Changelog for 0.10.0

- CHANGELOG.md
> [skip actions] - Release 0.11.0

- CHANGELOG.md
> [skip actions] Changelog updates for release 0.12.0

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/Mappers.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- e2e/payments.test.ts
- example/ios/Podfile.lock
- example/src/screens/CreateTokenScreen.tsx
- ios/Mappers.swift
- ios/StripeSdk.swift
- src/types/Token.ts
Add ability to create a PII token from a personal ID number
closes https://github.com/stripe/stripe-react-native/issues/878
Select one:
> feat: add option to create a PII token

- CHANGELOG.md
> [skip actions] Update changelog for 0.13.0 release

- CHANGELOG.md
> [skip actions] changelog for 0.13.1

- CHANGELOG.md
> Changelog update for release 0.14.0

- CHANGELOG.md
> Release 0.16.0

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/CollectBankAccountLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayPaymentMethodLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/main/java/com/reactnativestripesdk/utils/Extensions.kt
check for existence of fragment before removing
fixes https://github.com/stripe/stripe-react-native/issues/1053
Select one:
> fix: check for existence of fragment before removing

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/FinancialConnectionsSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/main/java/com/reactnativestripesdk/utils/Errors.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- e2e/FinancialConnections.test.ts
- e2e/screenObject/BasicPaymentScreen.ts
- e2e/screenObject/HomeScreen.ts
- example/package.json
- example/server/index.ts
- example/src/App.tsx
- example/src/screens/CollectBankAccountScreen.tsx
- example/src/screens/HomeScreen.tsx
- example/yarn.lock
- ios/Errors.swift
- ios/FinancialConnections.swift
- ios/Mappers.swift
- ios/StripeSdk.m
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/useFinancialConnectionsSheet.tsx
- src/hooks/useStripe.tsx
- src/index.tsx
- src/types/FinancialConnections.ts
- src/types/PaymentIntent.ts
- src/types/SetupIntent.ts
- src/types/Token.ts
- src/types/index.ts
added in the functionality found at: https://stripe.com/docs/financial-connections/connect-payouts?platform=ios
parity with native SDKs and closes https://github.com/stripe/stripe-react-native/issues/978
Select one:
> feat: Financial Connections sheet

- CHANGELOG.md
> [skip actions] changelog for 0.17.0

- CHANGELOG.md
> [skip actions] Changelog for 0.18.0

- CHANGELOG.md
> Update Changelog for 0.18.1

- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
use babel watch and nodemon for server, so there's no need to restart the server when there's changes / switched branch
Select one:
> [skip actions] use babel watch and nodemon for server

- example/ios/Podfile.lock
- ios/FinancialConnections.swift
- ios/Mappers.swift
- ios/StripeSdk.swift
- stripe-react-native.podspec
Constructs and sets a financial connections return url based on provided urlScheme 
App2app authentication support.
Select one:
> Sets return URL for connections based on urlScheme

- CHANGELOG.md
> Stripe React Native v0.20.0

- CHANGELOG.md
> Release stripe-react-native-0.21.0

- CHANGELOG.md
> [skip actions] Release 0.22.0

- example/ios/Podfile.lock
- src/index.tsx
- src/types/index.ts
- tsconfig.json
supersedes https://github.com/stripe/stripe-react-native/pull/1237
> fix: add and support isolatedModules TS option

- CHANGELOG.md
> Release 0.23.0

- CHANGELOG.md
> Release 0.23.3

- example/ios/Podfile.lock
- stripe-react-native.podspec
Upgrade stripe-ios dependency
bug fixes and unblocks https://github.com/stripe/stripe-react-native/pull/1248
> chore: upgrade stripe-ios

- CHANGELOG.md
> Release 0.27.0

- CHANGELOG.md
- README.md
> Release 0.27.1

- CHANGELOG.md
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/AuBECSDebitFormView.kt
- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
- android/src/main/java/com/reactnativestripesdk/CardFormView.kt
Upgrade to `20.24.+` and fix the build error.
Related `stripe-identity-react-native` change: https://github.com/stripe/stripe-identity-react-native/pull/119
Select one:
> update android to 20.24.+

- android/gradle.properties
- example/ios/Podfile.lock
- stripe-react-native.podspec
Updates android to 20.25.+
Updates ios to 23.8.+
> chore: update native libraries

- CHANGELOG.md
> [skip actions] release 0.27.2

- android/gradle.properties
- example/ios/Podfile.lock
- stripe-react-native.podspec
ios to 23.12
android to 20.28
fixes https://github.com/stripe/stripe-react-native/issues/1457
Select one:
> chore: update dependencies

- src/hooks/useFinancialConnectionsSheet.tsx
- src/hooks/usePaymentSheet.tsx
matches the rest of the hooks
fixes https://github.com/stripe/stripe-react-native/issues/1437
> fix: wrap the rest of the hook results in useCallback

- CHANGELOG.md
- ios/Mappers.swift
fixes https://github.com/stripe/stripe-react-native/issues/1445
> fix: return state in intent shipping details on iOS

- android/src/main/java/com/reactnativestripesdk/PaymentSheetAppearance.kt
Casts would silently fail
Select one:
> fix: some casts wouldn't work correctly on android and values would be ignored

- CHANGELOG.md
> Release - 0.31.0

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/GooglePayRequestHelper.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- example/src/screens/ApplePayScreen.tsx
- example/src/screens/GooglePayScreen.tsx
- ios/ApplePayViewController.swift
- src/functions.ts
- src/types/PlatformPay.ts
fixes https://github.com/stripe/stripe-react-native/pull/1367
Select one:
> feat: return shippingContact from `createPlatformPayPaymentMethod` and `createPlatformPayToken`

- CHANGELOG.md
- ios/StripeSdk.swift
fixes https://github.com/stripe/stripe-react-native/issues/1481
Select one:
> fix: cvc recollection on ios

- CHANGELOG.md
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/GooglePayLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayRequestHelper.kt
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- example/ios/Podfile.lock
- ios/Mappers.swift
- src/types/NextAction.ts
- src/types/PaymentSheet.ts
- src/types/PlatformPay.ts
- stripe-react-native.podspec
closes https://github.com/stripe/stripe-react-native/issues/1436
Select one:
> Update native libraries & add support for google pay amount & label params

- CHANGELOG.md
> Release 0.34.0

- CHANGELOG.md
> [skip actions] Update CHANGELOG.md for 0.35.0 release

- example/package.json
Renames the example app with the `@stripe/` prefix
Improves clarity!
CI
Select one:
> chore: Renames the sample app to use the `@stripe/` prefix

- CHANGELOG.md
> v0.37.0 release

- android/gradle.properties
- example/ios/Podfile.lock
- stripe-react-native.podspec
Just updating underlying ios and android libraries to the most recent versions to get bug fixes and new PMs
> chore: update native deps

- CHANGELOG.md
> Release v0.37.1

- android/gradle.properties
- example/ios/Podfile.lock
- example/ios/StripeSdkExample.xcodeproj/project.pbxproj
- stripe-react-native.podspec
> chore: update native libs

- CHANGELOG.md
> [skip actions] release 0.37.2

- CHANGELOG.md
> Stripe RN Release 0.37.3

- android/src/main/java/com/reactnativestripesdk/pushprovisioning/PushProvisioningProxy.kt
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/TapAndPayProxy.kt
We should also log these error messages to get a clearer picture of what's going on
> chore: include error messages in logs for push provisioning

- CHANGELOG.md
> Release v0.38.1

- CHANGELOG.md
> Release v0.38.2

- CHANGELOG.md
> Release v0.38.3

- android/src/main/java/com/reactnativestripesdk/GooglePayButtonManager.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonManager.kt
- example/ios/Podfile.lock
Fixes some build errors once you upgrade to RN 0.75.x
Select one:
> fix: RN 75 build errors

- CHANGELOG.md
> Release v0.38.5

- CHANGELOG.md
> release 0.39.0

- package.json
- scripts/publish
bumps the version, and also updates the script since we can't push directly to master anymore
Select one:
> [post-release] bump version to 0.40.0

- CHANGELOG.md
> Release v0.42.0

- package.json
released already, just updating package.json
Looks like we forgot to do this when releasing 0.41.0
> released v0.42.0

- CHANGELOG.md
This pull request updates the release notes for version 0.43 of the SDK.
```
**Features**
- Financial Connections now supports dark mode, and will automatically adapt to the device's theme. [Learn more](https://docs.stripe.com/financial-connections/other-data-powered-products?platform=react-native#connections-customize-react-native) about configuring appearance settings.
- Added card brand filtering to PaymentSheet and CustomerSheet to specify allowed or blocked card brands. [1857](https://github.com/stripe/stripe-react-native/pull/1857)
**Fixes**
- Updated `stripe-ios` to 24.7.\*
- Updated `stripe-android` to 21.6.\*
- Supports React Native 0.78
- Compatible with new architecture when bridgeless mode is disabled
```
Select one:
> Add release notes for 0.43

- scripts/publish
> fix: set upstream automatically in release flow

- CHANGELOG.md
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- example/ios/Podfile.lock
- ios/StripeSdk+PaymentSheet.swift
- src/types/PaymentSheet.ts
- stripe-react-native.podspec
This pull request adds a new optional `LinkParams` property to the PaymentSheet configuration.
[MOBILE_APIREVIEW-124](https://jira.corp.stripe.com/browse/MOBILE_APIREVIEW-124)
Select one: 
```
**Features**
- Added `LinkParams` to allow control over Link in PaymentSheet.
**Fixes**
- Updated `stripe-ios` to 24.11.\*
- Updated `stripe-android` to 21.9.\*
```
> Add `LinkParams` to PaymentSheet

- android/gradle.properties
This pull request updates to the latest version of the Android SDK, released [last week](https://github.com/stripe/stripe-android/releases/tag/v21.10.0).
Select one:
> Update Android SDK to 21.10

- CHANGELOG.md
This pull request is a follow-up to https://github.com/stripe/stripe-react-native/pull/1885, where I forgot to update the changelog.
Select one:
> Update changelog to mention correct Android version

- CHANGELOG.md
This pull request updates the release notes for v0.44.
Select one:
> Update changelog for 0.44

- package.json
update package.json for release
Select one:
> release v0.44.0

- ios/EmbeddedPaymentElementView.swift
- ios/PaymentOptionDisplayData+ReactNative.swift
- ios/PaymentSheetAppearance.swift
- ios/StripeSdk+Embedded.swift
- ios/StripeSdk+PaymentSheet.swift
- ios/StripeSdk.m
- ios/StripeSdk.swift
- Implements the bridge layer for embedded payment element on iOS
- Based on this prototype https://github.com/stripe/stripe-react-native/pull/1894/files?file-filters%5B%5D=.swift&show-viewed-files=true
- Embedded payment element
> Implement embedded for iOS

- android/build.gradle
- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementView.kt
- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementViewManager.kt
- android/src/main/java/com/reactnativestripesdk/PaymentOptionDisplayDataMapper.kt
- android/src/main/java/com/reactnativestripesdk/PaymentSheetAppearance.kt
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkPackage.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- Implements the bridge layer for embedded payment element on Android
- Based on this prototype https://github.com/stripe/stripe-react-native/pull/1894/files?file-filters%5B%5D=.kt&show-viewed-files=true
- Adds compose to our library
- Embedded payment element
> Implement bridge for RN Android

- e2e-tests/cardfield-basic.yml
- e2e-tests/embedded.yml
- example/src/App.tsx
- example/src/screens/EmbeddedPaymentElementScreen.tsx
- example/src/screens/HomeScreen.tsx
- src/index.tsx
- src/types/EmbeddedPaymentElement.tsx
- src/types/PaymentSheet.ts
- Adds the embedded react native API
- Will add an example app following this PR
- After this we just need to get the height updates working
https://docs.google.com/document/d/1Msn4YZZOAsDbz_Q7aGZCZuwhTmZJHjWqilKvR_ceWTI/edit?tab=t.0#heading=h.570u4leviueu
> Add JS Embedded APIs

- CHANGELOG.md
- android/gradle.properties
Update android minor version
Select one:
> Update android minor version

- README.md
Remove warning about new arch from README
We support the new arch now!
Select one:
> Remove warning about new arch from README

- ios/EmbeddedPaymentElementView.swift
- ios/NewArch/EmbeddedPaymentElementViewComponentView.h
- ios/NewArch/EmbeddedPaymentElementViewComponentView.mm
- package.json
- src/specs/NativeEmbeddedPaymentElement.ts
Implement missing new arch implementation on iOS for the new Embedded component.
Support new arch for Embedded on iOS.
Select one:
> Implement embedded on iOS new arch

- CHANGELOG.md
- README.md
Update changelog for v0.45, which was just released.
> Update the CHANGELOG for v0.45

- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementViewManager.kt
- example/src/screens/EmbeddedPaymentElementScreen.tsx
- Fixes a crash when allowsDelayedPaymentMethods is absent
- Bug fix
https://jira.corp.stripe.com/browse/MOBILESDK-3544
- CI
> Fix absent allowsDelayedPaymentMethods

- example/src/screens/EmbeddedPaymentElementScreen.tsx
> Handle confirm result in sample embedded app

- android/gradle.properties
- e2e-tests/android-only/local-only/paymentsheet-customFlow-cancel-before-timeout.yml
- e2e-tests/android-only/paymentsheet-canceled.yml
- e2e-tests/android-only/paymentsheet-customFlow-canceled.yml
- e2e-tests/customersheet.yml
- e2e-tests/ios-only/local-only/paymentsheet-customFlow-cancel-before-timeout.yml
- e2e-tests/ios-only/paymentsheet-canceled.yml
- e2e-tests/ios-only/paymentsheet-customFlow-canceled.yml
- e2e-tests/paymentsheet-basic.yml
- e2e-tests/paymentsheet-customFlow-decoupled.yml
- e2e-tests/paymentsheet-customFlow.yml
- e2e-tests/paymentsheet-decoupled.yml
- example/ios/Podfile.lock
- stripe-react-native.podspec
- Updates the native libs to most recent version
Select one:
> Update native libs

- CHANGELOG.md
> 0.47.0 proposal

- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementView.kt
Fix `Embedded` layout constraints for Android
Better constraint `Embedded` within its view
> Fix `Embedded` layout constraints for Android

- CHANGELOG.md
> 0.47.1 proposal

- CHANGELOG.md
> Propose 0.48.0 

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- e2e-tests/payment-sheet-pmo-sfu.yml
- example/server/index.ts
- example/src/App.tsx
- example/src/screens/HomeScreen.tsx
- example/src/screens/PaymentSheetDeferredIntentScreen.tsx
- example/src/screens/PaymentSheetWithPmoSfuScreen.tsx
- ios/StripeSdkImpl+PaymentSheet.swift
- src/types/PaymentIntent.ts
- src/types/PaymentSheet.ts
Add PMO SFU API for iOS and Android
https://jira.corp.stripe.com/browse/MOBILESDK-3580
Select one:
> Add PMO SFU API

- ios/OldArch/StripeSdkEventEmitterCompat.h
- ios/OldArch/StripeSdkEventEmitterCompat.m
- ios/StripeSdk.mm
- ios/StripeSdkEmitter.swift
- ios/StripeSdkImpl+Embedded.swift
- ios/StripeSdkImpl+PaymentSheet.swift
- ios/StripeSdkImpl.swift
> Add iOS CPM layer

- CHANGELOG.md
> 0.49.0 proposal

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentSheetAppearance.kt
- example/src/screens/EmbeddedPaymentElementImmediateActionScreen.tsx
- ios/PaymentSheetAppearance.swift
- We allow passing in a single color rather than just a light and dark. This fixes that.
- Bug fix
> Fix single color support EMPE

- src/types/EmbeddedPaymentElement.tsx
- src/types/PaymentSheet.ts
- correct misleading doc string for rowSelectionBehavior
- add additional info about default values where missing
Feedback from user about docs being confusing.
https://jira.corp.stripe.com/browse/MOBILESDK-3777
N/A
N/A
> Improve Embedded config docs

- CHANGELOG.md
> 0.50.3 proposal

- .github/workflows/e2e-tests.yml
- .github/workflows/js-tests.yml
- .github/workflows/unit-tests.yml
- Cancel previous CI runs
- Don't run CI on just .md file changes
> Improve CI quality of life

- example/ios/Podfile.lock
- stripe-react-native.podspec
> Update to latest iOS SDK.

- CHANGELOG.md
- package.json
> Release branch 18451 for 0.51.0

- example/server/onrampBackend.ts
- example/src/screens/CryptoOnrampScreen.tsx
> [Onramp] Add create auth intent, create onramp session and checkout.

- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
This pull request bumps the Android SDK to `21.26.+`.
Select one:
> Bump Android SDK version to 21.26.+

- example/src/screens/Onramp/CryptoOnrampFlow.tsx
- example/src/screens/Onramp/sections/OnrampResponseStatusSection.tsx
- example/src/screens/Onramp/sections/index.ts
- example/src/screens/Onramp/utils.ts
* Reduce duplication between payment functions.
* Centralize alert showing to allow easier refactoring / code reduction.
* Move response information to its own UI section.
Cleaning up code to allow for easier understanding / easier implementation.
> Crypto Onramp Example Refactoring

- example/ios/Podfile.lock
- stripe-react-native.podspec
Bump stripe-ios 24.24.1
Select one:
> [onramp] bump stripe-ios 24.24.1
