stripe/stripe-react-native

- .npmignore
- package.json
resolves #204 
as yarn doesn't support negations in package.json we need to use .npmignore for excluding certain files
> fix: use npmignore

- ios/StripeSdk.swift
Fixes #205 
When someone cancels the 3DS authentication window, on Android we map the PI status `requires_payment_method` to status `Failed`. 
This does the same for iOS so that it's coherent
> fix: unify cancel handling

- android/src/main/java/com/reactnativestripesdk/Mappers.kt
- ios/Mappers.swift
- src/types/ThreeDSecure.ts
> add missing 3ds button props

- CHANGELOG.md
- [#247](https://github.com/stripe/stripe-react-native/pull/247) feat: add `fontFamily` prop to `CardField` component ([#103](https://github.com/stripe/stripe-react-native/issues/103))
- [#245](https://github.com/stripe/stripe-react-native/pull/245) fix: clear card params when `CardField` input is invalidated ([#237](https://github.com/stripe/stripe-react-native/issues/237))
- [#228](https://github.com/stripe/stripe-react-native/pull/228) feat: add ability to show error in Apple Pay sheet within `onShippingContactSelected` handler ([#148](https://github.com/stripe/stripe-react-native/issues/148))
- [#221](https://github.com/stripe/stripe-react-native/pull/221) feat: add legacy `createToken` method for older integrations ([#187](https://github.com/stripe/stripe-react-native/issues/187))
- …
> chore: prepare release v0.1.2

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
Apps can crash if they haven't initialized stripe, and run code that triggers `BaseActivityEventListener.onActivityResult`, so the listener's content should be wrapped inside of `if (::stripe.isInitialized) {`
> fix: crash on onActivityResult if Stripe isn't initalized

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
It seems that the code using this param handled the possibility for `data` to be `null`, but it wasn't declared as a nullable type.
Encountered a crash while playing with another library which also spawned some activity which can return no data (ie `data = null`), but even so, it seemed that this param should've been declared with a nullable type.
> fix: make data param nullable for onActivityResult on android

- README.md
Been seeing a lot of confusion around the error `TypeError: null is not an object (evaluating '_NativeStripeSdk.default.initialise')` on Android when using Expo. Adding the solution to the troubleshooting section as it's not an obvious error.
> Added Expo Go update to troubleshooting

- android/src/main/java/com/reactnativestripesdk/Errors.kt
- android/src/main/java/com/reactnativestripesdk/Mappers.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/src/screens/SetupFuturePaymentScreen.tsx
- example/src/screens/WebhookPaymentScreen.tsx
- ios/Errors.swift
- ios/Mappers.swift
- ios/StripeSdk.m
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/helpers.ts
- src/types/Errors.ts
- src/types/PaymentIntents.ts
- src/types/SetupIntent.ts
> chore: improve response error object

- ios/Mappers.swift
When creating a payment method, the `vpa` parameter from the `Upi` payment methd is missing in iOS
[Mappers.swift#L548](https://github.com/stripe/stripe-react-native/blob/967bdbe78abe46c772e0ad68d084d83769075f6b/ios/Mappers.swift#L548)
React Native: 
https://github.com/stripe/stripe-react-native/blob/967bdbe78abe46c772e0ad68d084d83769075f6b/src/types/PaymentMethods.ts#L199-L201
Android:
https://github.com/stripe/stripe-react-native/blob/967bdbe78abe46c772e0ad68d084d83769075f6b/android/src/main/java/com/reactnativestripesdk/Mappers.kt#L298
> Fix UPI payment method on iOS

- android/build.gradle
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/ios/Podfile.lock
- ios/StripeSdk.swift
- src/functions.ts
- src/hooks/useStripe.tsx
- src/types/PaymentSheet.ts
- stripe-react-native.podspec
> feat: paymentsheet setupintents

- CHANGELOG.md
- [#309](https://github.com/stripe/stripe-react-native/pull/309) feat: add `retrieveSetupIntent` method ([#294](https://github.com/stripe/stripe-react-native/issues/294))
- [#306](https://github.com/stripe/stripe-react-native/pull/306) feat: add `dangerouslyGetFullCardDetails` prop to `CardField` component ([#280](https://github.com/stripe/stripe-react-native/issues/280))
- [#298](https://github.com/stripe/stripe-react-native/pull/298) feat: support SetupIntents in payment sheet ([#293](https://github.com/stripe/stripe-react-native/issues/293))
- [#296](https://github.com/stripe/stripe-react-native/pull/296) chore: support `testID` prop in all UI components ([#268](https://github.com/stripe/stripe-react-native/issues/268))
- [#295](https://github.com/stripe/stripe-react-native/pull/295) …
> chore: prepare release of v0.1.3

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/ios/Podfile.lock
- ios/StripeSdk.m
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/useConfirmPayment.tsx
- src/hooks/useStripe.tsx
- src/types/index.ts
It's creating some confusion that `functions` is exporting `confirmPaymentMethod` whereas `useStripe` is exporting `confirmPayment`: https://github.com/stripe/stripe-react-native/issues/318
This PR is unifying it and getting rid of `confirmPaymentMethod` across the board as it also doesn't make too much sense since one does confirm the payment intent, not the method.
> chore: rename confirmPaymentMethod to confirmPayment

- ios/StripeSdk.swift
Currently when you try to call `presentPaymentSheet` from a modal, the app will crash. This has been reported in a few issues (#315, #290).
I am not entirely sure if this fix doesn't breaks non-modal use-cases. But at least it worked correctly within a modal for our use-case with this modification.
> Allow payment sheets within modals

- android/src/main/java/com/reactnativestripesdk/StripeSdkCardView.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkCardViewManager.kt
- example/ios/Podfile.lock
- example/src/components/PaymentScreen.tsx
- ios/CardFieldManager.m
- ios/CardFieldManager.swift
- ios/CardFieldView.swift
- ios/StripeSdk.swift
- src/components/CardField.tsx
- src/types/components/CardFieldInput.ts
- expose CardField methods (focus, blur, clear)
- inject CardField reference to react-native InputState so the state of card field input can be handled via RN components like ScrollView
There is no need to use `StripeContainer` anymore since it's registered to RN InputState.
auto keyboard state example:
```
<ScrollView
keyboardShouldPersistTaps="never" // <-- add this line 
>
{children}
</ScrollView>
```
example of methods usage:
```
// App.js
const ref = useRef(null)
const handleFocus = () => {
ref.current.focus()
}
const handleBlur = () => {
ref.current.blur()
}
const handleClear = () => {
ref.current.clear()
}
return (
<CardField
ref={ref}
/>
)
```
> add imperative cardField methods (focus, blur, clear)

- ios/StripeSdk.swift
> fix: ignored url scheme when using paymentMethodId

- CHANGELOG.md
- android/build.gradle
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/ios/Podfile.lock
- example/src/screens/PaymentsUICompleteScreen.tsx
- stripe-react-native.podspec
- [#394](https://github.com/stripe/stripe-react-native/pull/394) **[BREAKING CHANGE]** fix: createToken response discrepancy ([#344](https://github.com/stripe/stripe-react-native/issues/344))
- [#354](https://github.com/stripe/stripe-react-native/pull/354) **[BREAKING CHANGE]** chore: rename top-level export `confirmPaymentMethod` to `confirmPayment` ([#318](https://github.com/stripe/stripe-react-native/issues/318))
- [#416](https://github.com/stripe/stripe-react-native/pull/416) fix(android): googlePay setting on initPaymentSheet
- [#392](https://github.com/stripe/stripe-react-native/pull/392) fix: `created` timestamp discrepancy ([#368](https://github.com/stripe/stripe-react-native/issues/368))
- [#395](https://github.com/stripe/stripe-react-native/pull/395) fix: resolve …
> chore: prepare release v0.1.5

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
Better error handling for createToken function. Now exceptions about not valid year or card number can be catched.
This is to stop issues like #405
> fix: better error handling for createToken - android

- ios/CardFieldDelegate.swift
- ios/CardFieldManager.swift
- ios/CardFieldView.swift
- ios/StripeSdk.swift
An attempt to fix #391
In order to fix the deallocation issue and make the code a little bit more readable I moved the CardFieldView reference from manager to StripeSdk. Thanks to that we don't have to cache anything in ViewManager and accessing card reference is easier from StripeSdk.
This solution works with assumption that there can only be one CardField rendered at once
TODO:
closes #391
> fix: removing usage of the map for cardview reference

- example/ios/Podfile.lock
- ios/CardFieldManager.swift
- ios/CardFieldView.swift
- ios/PaymentMethodFactory.swift
resolves #420 
for now postal code from CardField is not included in the payment.
This fix makes SDK to respect a postal code from CardField and takes it as a priority. 
Postal code still can be provided from a billing details when postal code field is disabled (`postalCodeEnabled={false}`)
> respect postal code from card field as a priority

- package.json
- src/plugin/__tests__/withStripe-test.ts
- src/plugin/withStripe.ts
- yarn.lock
Previously, if you applied the plugin and didn't provide any merchant IDs, it would create an empty array of merchant IDs:
```
<key>com.apple.developer.in-app-payments</key>
<array/>
```
Also upgraded the config-plugins package (no longer includes things like jimp, so should be significantly smaller)
> [plugin] fix: never set an empty merchant identifier array with plugin

- src/components/CardField.tsx
resolves #440 
this fix resolves issue which throws exception if certain TextInputState methods are not available since it has been added from 
react-native 0.63x.
> Unsupported text input method

- CHANGELOG.md
- example/src/screens/AfterpayClearpayPaymentScreen.tsx
- example/src/screens/AlipayPaymentScreen.tsx
- example/src/screens/ApplePayScreen.tsx
- example/src/screens/AuBECSDebitPaymentScreen.tsx
- example/src/screens/AuBECSDebitSetupPaymentScreen.tsx
- example/src/screens/BancontactPaymentScreen.tsx
- example/src/screens/EPSPaymentScreen.tsx
- example/src/screens/FPXPaymentScreen.tsx
- example/src/screens/GiropayPaymentScreen.tsx
- example/src/screens/GrabPayPaymentScreen.tsx
- example/src/screens/IdealPaymentScreen.tsx
- example/src/screens/OxxoPaymentScreen.tsx
- example/src/screens/P24PaymentScreen.tsx
- example/src/screens/PaymentResultScreen.tsx
- example/src/screens/SepaPaymentScreen.tsx
- example/src/screens/SetupFuturePaymentScreen.tsx
- example/src/screens/SofortPaymentScreen.tsx
- src/components/ApplePayButton.tsx
- src/components/AuBECSDebitForm.tsx
- src/functions.ts
- src/hooks/useApplePay.tsx
- src/hooks/useGooglePay.tsx
- src/hooks/useStripe.tsx
- src/plugin/__tests__/withStripe-test.ts
- wdio.ios.js
- [#415](https://github.com/stripe/stripe-react-native/pull/415) feat: add multiline card form element ([#83](https://github.com/stripe/stripe-react-native/issues/83))
- [#441](https://github.com/stripe/stripe-react-native/pull/441) feat(android): add standalone Google Pay ([#9](https://github.com/stripe/stripe-react-native/issues/9))
- [#422](https://github.com/stripe/stripe-react-native/pull/422) feat: add WeChat Pay ([#52](https://github.com/stripe/stripe-react-native/issues/52))
- [#453](https://github.com/stripe/stripe-react-native/pull/453) chore: add JCB support for Apple Pay ([#43](https://github.com/stripe/stripe-react-native/issues/430))
- [#451](https://github.com/stripe/stripe-react-native/pull/451) fix: send postal code with card details …
> chore: prepare release v0.2.0

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
While payment sheet is in custom flow `presentPaymentSheetPromise` is called twice, on `ON_PAYMENT_OPTION_ACTION` and `ON_PAYMENT_RESULT_ACTION` intents.
This breaks the flutter plugin, as the promised is expected to be returned only once.
> Fix custom flow.

- example/ios/Podfile.lock
- example/src/screens/PaymentsUICompleteScreen.tsx
- example/src/screens/PaymentsUICustomScreen.tsx
- ios/Errors.swift
- ios/StripeSdk.swift
> Enhance payment sheet DX

- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/ios/Podfile.lock
- example/src/screens/PaymentsUICompleteScreen.tsx
- example/src/screens/PaymentsUICustomScreen.tsx
- ios/StripeSdk.m
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/usePaymentSheet.tsx
- src/hooks/useStripe.tsx
- src/types/PaymentSheet.ts
Right now presentPaymentSheets has two params:
- `clientSecret` not used anywhere
- `confirmPayment`, used to differentiate between single-step and multipe-step payment sheets.
This last param is not very clear for developers as it always needs to be the opposite of the param `customFlow` from initPaymentSheet. This could be simplified to inherit the config from initPaymentSheet, or otherwise explain better and throw an error in the case  `customFlow` and `confirmPayment` are the same.
My proposal is to remove both params. This would look like the native implementations that don't need any params in the respective methods
> Simplify present payment sheet

- ios/StripeSdk.swift
The createToken call was only using the cardFieldView when trying to create the token on iOS. 
I am having trouble running the android project, so didn't test it out there. Do note that the [code](https://github.com/stripe/stripe-react-native/blob/c6ca57bea9217dbaf656b887323457002ca57495/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt#L404) suggests it's already working fine in Android.
> fix: adds cardFormView to the createToken

- ios/StripeSdk.m
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/useApplePay.tsx
- src/hooks/useStripe.tsx
- src/types/index.ts
> add openApplePaySetup method

- android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt
Fixes #528 
Now we are waiting for both callbacks (from `GooglePayMethodLauncher` and `GooglePayLauncher`) to be called in order to send onReady event.
> feat: improve handling onGooglePayReady callback

- android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
> resolve initGooglePay with error if it's not available

- ios/StripeSdk.swift
> split apple pay address by new line

- CHANGELOG.md
- [#548](https://github.com/stripe/stripe-react-native/pull/548) chore: split apple pay address by new line ([#531](https://github.com/stripe/stripe-react-native/issues/531))
- [#546](https://github.com/stripe/stripe-react-native/pull/546) fix: resolve initGooglePay with error if it's not available ([#533](https://github.com/stripe/stripe-react-native/issues/533))
- [#525](https://github.com/stripe/stripe-react-native/pull/525) feat: add `openApplePaySetup` method ([#400](https://github.com/stripe/stripe-react-native/issues/400))
- [#521](https://github.com/stripe/stripe-react-native/pull/521) fix: support cardFormView for createToken method
- [#514](https://github.com/stripe/stripe-react-native/pull/514) feat: simpify `presentPaymentSheet`
- …
> chore: prepare release v0.2.1

- CHANGELOG.md
- [#588](https://github.com/stripe/stripe-react-native/pull/588) fix: use the LocalBroadcastManager ([#588](https://github.com/stripe/stripe-react-native/issues/588))
> chore: prepare release v0.2.2

- README.md
- jest/mock.js
- jest/stripe-react-native-mock.js
- package.json
- src/hooks/useConfirmSetupIntent.tsx
> add jest mock file

- src/types/GooglePay.ts
Tiny documentation correction for the [existingPaymentMethodRequired](https://github.com/stripe/stripe-react-native/blob/master/src/types/GooglePay.ts#L51)  param which suggests it defaults to `true` where it actually defaults to `false`.
Source: https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt#L53
> docs: Correct default for existingPaymentMethodRequired

- android/src/main/java/com/reactnativestripesdk/CardChangedEvent.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkCardView.kt
- ios/CardFieldView.swift
- ios/Mappers.swift
- src/components/CardField.tsx
- src/types/components/CardFieldInput.ts
Closes #423 
This adds three new fields to the card details returned by `onCardChange`: `validCVC`, `validExpiryDate`, and `validNumber`. On iOS, each field has a possible value of "Valid", "Invalid", "Incomplete", and "Unknown". The Android SDK doesn't seem to expose whether a field is incomplete or not, so Android has "Valid", "Invalid", and "Unknown".
This is my first time working on a native module so I'm not 100% on the Swift and Kotlin syntax, let me know if there's a better way to write this and I'll update it
> feat: Add validation state to CardField (#423)

- android/build.gradle
Currently the gradle file requires 18.1.0, but I'm thinking we should allow for wildcard matching on the minor version so we can get minor version updates for free.
On iOS we use the optimistic operator in the podspec so we will get minor updates for free on iOS.
> Depend on any minor version of Stripe Android 18.1.x

- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- src/types/PaymentSheet.ts
Necessary to support Setup Intents including Google Pay
```
const { error } = await initPaymentSheet({
customerId: customer,
customerEphemeralKeySecret: ephemeralKey,
setupIntentClientSecret: setupIntentClientSecret,
customFlow: false,
merchantDisplayName: 'Example Inc.',
applePay: true,
merchantCountryCode: 'US',
currencyCode: 'USD', // this is required for setup intents
style: 'automatic',
googlePay: true,
testEnv: true,
primaryButtonColor: '#635BFF', // Blurple
returnURL: 'stripe-example://stripe-redirect',
defaultBillingDetails: billingDetails,
allowsDelayedPaymentMethods: true,
});
```
> Add `currencyCode` support to initPaymentSheet for Google Pay & Setup Intents

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/StripeSdkCardView.kt
- example/src/screens/NoWebhookPaymentScreen.tsx
`cursorColor` wasn't being assigned on Android. `setTint` was added in Android 10 to programmatically change this color without relying on any XML, so let's use that.
On android, there's a bit more granularity, but **to match iOS** I think we should apply cursorColor to the highlight and the textSelectHandles.
android:
ios:
fixes https://github.com/stripe/stripe-react-native/issues/766, parity with iOS
Select one:
> fix: properly configure cursorColor for CardField on Android

- CHANGELOG.md
- android/build.gradle
- android/src/main/java/com/reactnativestripesdk/GooglePayPaymentMethodLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- docs/GooglePay.md
- example/android/app/build.gradle
- example/src/screens/GooglePayScreen.tsx
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/useGooglePay.tsx
- src/hooks/useStripe.tsx
- src/types/GooglePay.ts
Currently people need to `initGooglePay` and `catch` an error to find out if the device supports Google pay, which isn't great. By adding this method, we have parity with the native wallets on android and ios (which offers `isApplePaySupported`).
Closes https://github.com/stripe/stripe-react-native/issues/683 (popular feature request)
This PR also closes https://github.com/stripe/stripe-react-native/issues/607, and closes https://github.com/stripe/stripe-react-native/issues/617, and closes https://github.com/stripe/stripe-react-native/issues/725
Select one:
> Feat: add `isGooglePaySupported` method

- ios/StripeSdk.swift
On iOS, the "custom-flow"-PaymentSheet is presented also for "non-custom-flow"-PaymentSheets after it has been opened once during the session. In order to fix this bug, I added `self.paymentSheetFlowController = nil` in `initPaymentSheet` when `customFlow == false` in order to open the correct PaymentSheet in `presentPaymentSheet` later on.
Fixes #608 
Select one:
> fix: incorrect payment sheet shown

- android/build.gradle
- example/ios/Podfile.lock
- stripe-react-native.podspec
Upgrade stripe-ios to 21.12.0
Upgrade stripe-android to 19.2.+. We may soft-match the minor version eventually, but I say we keep it as is for now
Get new bugfixes available in both libs
CI should pass
Select one:
> chore: Upgrade native Stripe dependencies

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- e2e/payments.test.ts
- e2e/screenObject/HomeScreen.ts
- example/src/App.tsx
- example/src/screens/CreateTokenScreen.tsx
- example/src/screens/HomeScreen.tsx
- src/functions.ts
- src/types/Errors.ts
Android apps would crash if routing number passed was an empty string, so now we default to null. Also added a check to help out folks in the US- routing numbers **are** required for US bank accounts.
Additionally, the `runCatching` block wasn't catching errors thrown inside of `CoroutineScope`, so moved that inside the block.
Fixes https://github.com/stripe/stripe-react-native/issues/807
Select one:
> fix: pass null instead of empty string for routing number

- .github/workflows/e2e-tests.yml
- android/src/main/java/com/reactnativestripesdk/StripeSdkCardView.kt
- example/index.js
closes #121
`cardParams`, `paymentMethodCreateParams` and `paymentMethodCard` properties have the side effect that when called it will shift the focus to an invalid field. In order to avoid this, we  need to call it only when the card details are valid.
> [Android] fix: card field focus jumps back to the card number field

- CHANGELOG.md
- example/ios/Podfile.lock
- example/src/screens/AuBECSDebitSetupPaymentScreen.tsx
- ios/AuBECSDebitFormView.swift
Added support for `placeholderColor`, `textErrorColor `, `borderColor`, `borderRadius`, and `borderWidth` for `AuBECSDebitForm` on iOS
Platform compatibility- these styles were supported on Android, but not on iOS
Select one:
> feat: add ios support for all aubecsform styles

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/src/screens/CreateTokenScreen.tsx
- ios/Mappers.swift
- ios/StripeSdk.swift
- src/types/index.ts
Add support for setting `currency` in a card token
https://jira.corp.stripe.com/browse/RUN_DX-1037
Select one:
> feat: add currency support when creating card tokens

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/Mappers.kt
- ios/Mappers.swift
- src/types/Card.ts
add card.id and bankaccount.id to returned maps from `createToken`
closes https://github.com/stripe/stripe-react-native/issues/671
Select one: 
- via typescript
> feat: add card ID and bankAccount ID to token response

- android/build.gradle
Upgrade appcompat dependency
Match stripe-android version, and this should be upgraded before RN 68 release anyways.
Select one:
> chore: upgrade to appcompat 1.4.1

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/CollectBankAccountLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/Constants.kt
- android/src/main/java/com/reactnativestripesdk/Errors.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayPaymentMethodLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
We weren't always appropriately null-checking `currentActivity`, and the typecast could result in crashes. We now resolve with a consistent and useful error telling the user they can retry the method.
closes https://github.com/stripe/stripe-react-native/issues/844 and I'm sure other instances of crashes on Android
closes https://github.com/stripe/stripe-react-native/issues/881
Select one:
> fix: add check to avoid crashes when currentActivity is null

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/AuBECSDebitFormViewManager.kt
- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
- android/src/main/java/com/reactnativestripesdk/CardFieldViewManager.kt
- android/src/main/java/com/reactnativestripesdk/CardFormViewManager.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayButtonManager.kt
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeContainerManager.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
first commit- just resolving some warnings in Android Studio
second commit- move focus change logic from `CardInputListener` to each individual edit text's `onFocusChangeListener`
https://jira.corp.stripe.com/browse/DX-7349
closes https://github.com/stripe/stripe-react-native/issues/734
Select one:
> fix: onBlur callback on CardField

- babel.config.js
babel plugin identifies import declarations that need to be modified for transpilation. right now, that's only the `../../package.json` import
fixes https://github.com/stripe/stripe-react-native/issues/841
run `yarn prepare` with these changes, and `lib/commonjs/components/StripeProvider.js` and `lib/module/components/StripeProvider.js` have the correct file path
> fix: create custom babel plugin for package.json imports in `src/`

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/Mappers.kt
include `fingerprint` in the Card result on android
closes https://github.com/stripe/stripe-react-native/issues/907
Select one:
> fix: add fingerprint to Card result on android

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/Mappers.kt
- example/ios/Podfile.lock
Previously, you had to pass billingDetails to capture zipcode from CardFieldView (which doesn't make much sense)
It's a bug, people should be able to rely on CardField for zip code and pass null for `billingDetails`
Select one:
> fix: Providing zip code straight from CardField component on Android

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonManager.kt
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonView.kt
- e2e/payments.test.ts
- e2e/screenObject/BasicPaymentScreen.ts
- example/ios/Podfile.lock
- example/ios/StripeSdkExample.xcodeproj/project.pbxproj
- example/src/screens/ACHPaymentScreen.tsx
- example/src/screens/ACHSetupScreen.tsx
- example/src/screens/ApplePayScreen.tsx
- example/src/screens/GooglePayScreen.tsx
- ios/pushprovisioning/AddToWalletButtonManager.m
- ios/pushprovisioning/AddToWalletButtonView.swift
- src/components/AddToWalletButton.tsx
- stripe-react-native.podspec
Modified the props for the `AddToWalletButton` component. Instead of passing `cardHolderName`, `cardLastFour`, `cardDescription`, and `cardBrand` directly as props, you will instead pass a `cardDetails` prop, which is an object containing the following fields:
- `primaryAccountIdentifier`: The `wallet.primary_account_identifier` value from the issued card.
- `name`: The card holder name (previously `cardHolderName`).
- `description`: A user-facing description of the card (previously `cardDescription`).
- `lastFour`: Last 4 digits of the card, optional (previously `cardLastFour`).
- `brand`: The card brand, optional (previously `cardBrand`).
Stripe iOS [recently updated to expose a method that sets the `primaryAccountIdentifier`](https://stripe.com/docs/issuing/cards/digital-wallets?platfor …
> breaking: use a cardDetails prop for AddToWalletButton component

- babel.config.js
- example/ios/Podfile.lock
https://github.com/stripe/stripe-react-native/pull/902 introduced a fix, but it didn't work because it was modifying the value of `importResource` and wasn't (by reference) modifying `path.node.source.value`
manually checked the build files
Select one:
> fix: correctly overwrite package.json import via babel

- CHANGELOG.md
- README.md
- e2e/screenObject/BasicPaymentScreen.ts
- example/ios/Podfile.lock
- example/server/index.ts
- stripe-react-native.podspec
Updated stripe-ios dependency & example server
to support `us_bank_account` in the payment sheet
Select one:
> feat: add ACHv2 to payment sheet on iOS

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
Added forwarding of activity result to the paymentLauncherFragment
Without this, only on older versions of RN, the result is never passed to the fragment and promises would never resolve for calls to `confirmSetupIntent` and `confirmPayment`. 
It should be noted that this _can_ duplicate calls to the payment result callback, but it's not really an issue since calling `promise.resolve` on an _already resolved_ promise is a no-op. 
When we don't want to support RN 64 and below anymore, I believe these three lines can be removed.
Select one:
> fix: manually forward activity results to paymentLauncherFragment

- android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt
- e2e/payments.test.ts
- example/src/screens/SetupFuturePaymentScreen.tsx
Adds the ability to confirm card payments via either a paymentMethodId or a token on Android (already exists on iOS)
closes https://github.com/stripe/stripe-react-native/issues/643
Select one: 
- [] I have added relevant documentation for my changes.
> feat: add token & paymentMethodId handling to confirmPayment for Cards

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/CollectBankAccountLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayPaymentMethodLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
To avoid the crash detailed in https://github.com/stripe/stripe-react-native/issues/887, we can move the "optional" commits over to `commitAllowingStateLoss`, since it's not really a terrible event if those two commits are lost, they're essentially cleanup. 
The other instances are all in exposed React methods, so if we encounter this error we should resolve the promise with an error, and then the user can handle that as they wish (AKA retry)
fixes https://github.com/stripe/stripe-react-native/issues/887
Select one:
> fix: wrap instances of framentManager.commit (or use commitAllowingStateLoss)

- android/src/main/java/com/reactnativestripesdk/Constants.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
We used to rely on LocalBroadcastManager to send/receive intents in order to resolve promises based on behavior in fragments.
We don't need to rely on intents for this: it's confusing, more bug prone, and although it's safe to use LocalBroadcastManager, some folks assume we're using BroadcastManager which is **not** secure (to be clear, we are NOT using BroadcastManager).
Select one:
> chore: Remove usage of LocalBroadCastManager

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/Errors.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
safe cast Throwables as Exceptions
We can pull the expected fields out of Exceptions, giving more info on error events
Select one:
> fix: pull error info from Throwables on Android

- CHANGELOG.md
- example/src/screens/PaymentSheetAppearance.ts
- ios/PaymentSheetAppearance.swift
- src/types/PaymentSheet.ts
rename `appearance.shadow.borderRadius` to `appearance.shadow.blurRadius`
also fixed the offset to have the component itself be the origin (0,0), and behavior matches the docstring example now
More descriptive of what's actually being changed. same behavior as https://developer.apple.com/documentation/quartzcore/calayer/1410819-shadowradius
Select one:
> fix: rename appearance.shadow.borderRadius to appearance.shadow.blurRadius

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/ios/Podfile.lock
Previously we were instantiating payment launcher on SDK initialization. Now, we init whenever we need, and then tear down the Fragment afterwards
closes https://github.com/stripe/stripe-react-native/issues/930
closes https://github.com/stripe/stripe-react-native/issues/968
Select one:
> fix: instantiate PaymentLauncher as needed instead of on init

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- ios/StripeSdk.swift
- src/functions.ts
- src/types/index.ts
previously we'd return with a null error, and a null payment option is the flow was cancelled. this isn't necessarily bad, but it doesn't match the behavior of the non-custom flow, or any of our other flows.
Now, we resolve with an error.code == Canceled
closes https://github.com/stripe/stripe-react-native/issues/723
Select one:
> fix: resolve with Error.Canceled if no payment option is selected in Payment Sheet custom flow

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/CardFormView.kt
- android/src/main/java/com/reactnativestripesdk/CardFormViewManager.kt
- example/src/screens/MultilineWebhookPaymentScreen.tsx
- src/components/CardForm.tsx
- src/types/components/CardFormView.ts
`CardForm`'s country input on Android will now match the behavior of iOS- defaulting to the current locale of the device (user setting). This PR also adds new functionality- the option to override that input on Android (iOS doesn't expose this)
closes https://github.com/stripe/stripe-react-native/issues/695
Select one:
> feat,fix: CardForm country input defaults to current region on Android, add option to override

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
- android/src/main/java/com/reactnativestripesdk/CardFieldViewManager.kt
- example/ios/Podfile.lock
- ios/CardFieldManager.m
- ios/CardFieldView.swift
- src/components/CardField.tsx
- src/types/components/CardFieldInput.ts
previously, the `complete` field in the `onCardChange` callback would incorrectly be set to `true` if the postal code wasn't filled out on Android (not ios). This fixes that, and also implements the same behavior as ios- if the user's current device locale is a country/region without postal codes, the postal code entry isn't shown or required. 
Users can also override the country code by passing the `countryCode` prop
Select one:
> fix: Make CardField postal code behavior consistent on iOS and Android

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
- android/src/main/java/com/reactnativestripesdk/CardFieldViewManager.kt
Previously we'd show the postal code if the `countryCode` was set to a country that does require postal codes, even if `postalCodeEnabled` was false.
fix small bug intro'd in 0.13.0
Select one:
> fix: Never show postal code input in `CardField` if `postalCodeEnabled=false` (regardless of `countryCode`)

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
return the card brand as soon as we know it, match iOS
fixes https://github.com/stripe/stripe-react-native/issues/714
Select one:
> fix: return card brand as soon as possible in CardField onCardChange callback

- ios/CardFieldView.swift
we were relying on textField.cardParams.XYZ in cases where we could just rely on direct `textField` properties. These properties seem to be kept in a better state, based on the expiry date keeping more in sync when testing fixes for the linked issue
fixes https://github.com/stripe/stripe-react-native/issues/1018
https://user-images.githubusercontent.com/97612659/176005692-ac6f408e-b652-4c67-8446-42d3146ce744.mov
> fix: remove reliance on cardparams where we can pull data directly from textField

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
Previously we would remove the payment sheet fragment after the result callback completed. But if customers cancel and then launch the same payment sheet again, this would cause an issue. Now, if the payment succeeds, we know we can remove the fragment. Otherwise, we don't remove it until a new payment sheet is being initialized (there are never two payment sheets initialized at once)
fixes https://github.com/stripe/stripe-react-native/issues/999
Select one:
> fix: don't aggressively remove payment sheet fragment

- android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/ios/Podfile.lock
Added support for all the payment methods we currently support via other functions (like `confirmPayment`) to be supported via the `createPaymentMethod` function. 
closes https://github.com/stripe/stripe-react-native/issues/642
Cleans up a lot of the logic in `[PaymentMethodCreateParamsFactory.kt](https://github.com/stripe/stripe-react-native/pull/987/files#diff-9eb0ba7715e0870bce660045f3334fdf6e7b14a32606b63229033597ce125e35)` so that it's simpler, shorter, and more extensible.
Select one:
> fix: support all payment methods in `createPaymentMethod` on Android

- .npmignore
- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/AuBECSDebitFormView.kt
- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
- android/src/main/java/com/reactnativestripesdk/CardFormView.kt
- android/src/main/java/com/reactnativestripesdk/CollectBankAccountLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt
- android/src/main/java/com/reactnativestripesdk/PaymentSheetAppearance.kt
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonView.kt
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/PushProvisioningProxy.kt
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/TapAndPayProxy.kt
- android/src/main/java/com/reactnativestripesdk/utils/Errors.kt
- android/src/main/java/com/reactnativestripesdk/utils/Extensions.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- android/src/main/java/com/reactnativestripesdk/utils/PostalCodeUtilities.kt
Adds InputFilters to postal code edit texts for CardForm and CardField.
https://en.wikipedia.org/wiki/Postal_code#Character_sets
Also created a utils/ directory in the android source in this PR just to clean up a bit as we go
fixes a bug, makes behavior consistent with iOS
Select one:
> fix: postal code inputs no longer accept characters that are never present in postal codes

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- ios/StripeSdk.swift
Fixed an issue on older version of React Native where calling `collectBankAccountForSetup` or `collectBankAccountForPayment` and getting a `Canceled` result could cause a crash. Simplified some other logic as well around resolving promises
fixes a bug reported by a user
Select one:
> fix: ensure all promises are only ever resolved once to fix older versions of react native

- CHANGELOG.md
> [skip actions] v0.15.0

- CHANGELOG.md
- example/ios/Podfile.lock
- ios/CardFormView.swift
- src/components/CardForm.tsx
configure the CALayer's borderColor and borderRadius, and the UIView's tintColor (which `STPCardFormView` uses for the cursor color)
partially addresses https://github.com/stripe/stripe-react-native/issues/563
Select one:
> feat: add support for additional cardStyles in CardForm on iOS

- .husky/pre-commit
- android/build.gradle
- example/android/app/build.gradle
- example/android/app/src/main/java/com/example/reactnativestripesdk/MainActivity.java
- example/android/app/src/main/java/com/example/reactnativestripesdk/newarchitecture/MainApplicationReactNativeHost.java
- example/android/app/src/main/jni/Android.mk
- example/android/build.gradle
- example/android/settings.gradle
- example/ios/.xcode.env
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/StripeSdkExample.xcodeproj/project.pbxproj
- example/ios/StripeSdkExample/AppDelegate.mm
- example/package.json
- example/yarn.lock
- package.json
- yarn.lock
This PR upgrades:
- react
- react-native
- appium
- @expo/config-plugins
- adds a resolution for simple-plist to resolve a security notice
upgrade example app to the most recent stable release of RN, and close out some of our dependabot security vulns (none of which are worrisome, just keeping it clean)
Select one:
> chore: Upgrade react-native in example app and a few other dependencies

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/ios/Podfile.lock
Fixes an issue where `collectBankAccountForPayment` and `collectBankAccountForSetup` would fail on Android when using React Native 0.65.x or under.
On rn 0.65 and under, there seems to be a bug where these activity results aren't passed to fragments. 
Select one:
> fix: pass activity result down to collectBankAccountLauncherFragment

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- ios/Errors.swift
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/useConfirmPayment.tsx
- src/hooks/useStripe.tsx
allows merchants to confirm a payment intent that has had the payment method attached on the server side
closes https://github.com/stripe/stripe-react-native/issues/614
Select one:
> feat: allow confirmPayment to be called without payment method

- CHANGELOG.md
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/CollectBankAccountLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/FinancialConnectionsSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- example/ios/Podfile.lock
- stripe-react-native.podspec
Upgraded native stripe-android library, and pass down the `stripeAccountId` to both `CollectBankAccountLauncher` and `FinancialConnectionsSheet.Configuration`. Also upgraded iOS since a new version was released. 
Fixed a bug on Android where `collectBankAccountForPayment`, `collectBankAccountForSetup`, `collectBankAccountToken`, and `collectFinancialConnectionsAccounts` wouldn't work with Stripe Connect accounts. 
no user-facing changes required to get this fix
> fix: Android FinancialConnections functionality not working for Connect accounts

- CHANGELOG.md
- example/server/index.ts
- example/src/screens/NoWebhookPaymentScreen.tsx
- ios/StripeSdk.m
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/useStripe.tsx
handleNextAction wasn't redirecting back to the app on iOS. This is bc the return URL has to match the `return_url` set during payment intent creation on the server (which our SDK will never know). So, this is now exposed as an optional parameter (no breaking change). 
Docs changes to https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native will follow
closes https://github.com/stripe/stripe-react-native/issues/772
Select one:
> feat: expose returnURL parameter for handleNextAction

- example/src/components/PaymentScreen.tsx
- example/src/screens/HomeScreen.tsx
`safepay` is appended to the url scheme in a couple cases in the SDK in order to form a valid url to pass as a `returnURL`. However, there is no need for the client to be aware of this, since the `handleURLCallback` function returns a promise that resolves to a boolean indicating whether or not stripe handled that URL. Merchants can check that value, and if its false, it was not a Stripe url – handle the URL normally as you would
closes https://github.com/stripe/stripe-react-native/issues/1101
Select one:
> chore: remove 'safepay' reference from client side code

- example/ios/Podfile.lock
- ios/Errors.swift
Before this, merchants would get an error back saying to "try again in a few minutes", rather than the real actionable error (invalid param or something like that)
https://github.com/stripe/stripe-react-native/issues/1096
Select one:
> fix: throw underlying error, not surface error

- CHANGELOG.md
- package.json
- yarn.lock
closes https://github.com/stripe/stripe-react-native/issues/1108
Select one:
> fix: expo config plugin version

- README.md
As the eslint says: "Did you mean to use ':'? '=' can only be after a property name when the containing object literal is part of a destructuring pattern.".
In the docs at ``Stripe initialization`` section, the object declaration syntax is incorrect.
I was looking for help then I found this. I imagine this fix can help someone in the future. ~Also I love Stripe <3~
You can see the diff below:
```import { initStripe } from '@stripe/stripe-react-native';
function App() {
// ...
useEffect(() => {
initStripe({
publishableKey: publishableKey,
merchantIdentifier: 'merchant.identifier',
CORRECT 👇
urlScheme: "your-url-scheme",
urlScheme="your-url-scheme",
INCORRECT👆 (current)
});
}, []);
}
```
Select one:
> fix(docs): incorrect way to use key-value object

- CHANGELOG.md
- README.md
> Release 0.19.0

- CHANGELOG.md
- ios/StripeSdk.swift
Fixes an issue on iOS where `confirmSetupIntent` would throw an error if the `Card` payment method was provided with the `paymentMethodId` parameter. We weren't checking for this before.
closes https://github.com/stripe/stripe-react-native/issues/1124
Select one:
> fix: confirmSetupIntent with paymentMethodId shouldn't throw an error

- README.md
Updated docs.
When following these [troubleshooting instructions](https://github.com/stripe/stripe-react-native#undefined-symbols-for-architecture-x86_64-on-ios), at the "Create a new Swift file..." step, XCode was not prompting me to create a bridging header. It turns out you must check the appropriate Target for this dialog to appear. I have updated the instructions accordingly.
Select one:
> docs: Update Troubleshooting instructions for creating a new Swift file

- ios/FinancialConnections.swift
these fields were internal before, so we couldn't pass them back
make ios api consistent with android
Select one:
> fix: expose account balance cash and credit on iOS

- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
- android/src/main/java/com/reactnativestripesdk/CardFormView.kt
The dimension values coming from the JS side should be regarded as DIP values and be properly converted. This PR handles the `borderWidth` and `borderRadius` values with the `PixelUtil.toPixelFromDIP` util function provided by React Native. See [the similar usage in RN's codebase](https://github.com/facebook/react-native/blob/5449148482271d60c87f6e5fa4483e69d4410320/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java#L130).
#1181 
| CardField | CardForm |
| ------------- | ------------- |
| ![Screenshot_20221024_112115](https://user-images.githubusercontent.com/7088631/197443539-4340b143-99df-4c09-a77a-55379b804567.png) | ![Screenshot_20221024_112417](https://user-images.githubusercontent.com/7088631/197443551-3dfdfb61-ec5a-4726-9a7c-7982c05ad366.png) |
| …
> fix: fix inconsistent border width and radius on Android (#1181)

- android/build.gradle
Removed jCenter repository references from build.gradle to use mavenCentral
Fixes #1186 
We are not anymore able to build our android app because jCenter is unavailable
Select one:
> fix: use mavenCentral repository instead of jCenter

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- e2e/FinancialConnections.test.ts
- e2e/buyNowPayLater.test.ts
- e2e/screenObject/BasicPaymentScreen.ts
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/StripeSdkExample.xcodeproj/project.pbxproj
- example/src/screens/PaymentsUICompleteScreen.tsx
- ios/ApplePayUtils.swift
- ios/CardFieldView.swift
- ios/Mappers.swift
- ios/PaymentMethodFactory.swift
- ios/PaymentSheetAppearance.swift
- ios/StripeSdk.swift
- src/types/PaymentSheet.ts
- stripe-react-native.podspec
- wdio.android.js
Allow merchants to customize the call to action button in payment sheet. This will also apply to apple pay once https://github.com/stripe/stripe-react-native/pull/1164 lands
This PR also upgrades to stripe-ios 23, which completes prework for splitting our SDK into smaller distinct modules.
fixes https://github.com/stripe/stripe-react-native/issues/836
Select one:
> feat: add call to action button label configuration to initPaymentSheet

- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
fix: 'when' expression must be exhaustive, add necessary 'UpiAwaitNotification' branch or 'else' branch instead
When upgrading Kotlin version to 1.7.10, this error show up. So an 'else' condition is added in order to make the library compile again. It could easily be another specific case that contemplates 'UpiAwaitNotification' as well.
When upgrading Kotlin version to 1.7.10, this error show up. So an 'else' condition is added in order to make the library compile again. It could easily be another specific case that contemplates 'UpiAwaitNotification' as well.
I believe this is a needed change for the library compatibility with Kotlin 1.7.10 new version. At least it was necessary for my project to build again.
- [ x ] I tested this manually
Select one: 
- [ x ] I have added relevant …
> fix: 'when' expression must be exhaustive. Kotlin 1.7.10

- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
Issue: https://github.com/stripe/stripe-react-native/issues/1146
Order of react props apply is not as expected:
setCountryCode applied first, then setPostalCodeEnabled. As postalCodeEnabled is true by default, it leads to issues with postalCodeEnabled={false} on react side.
Safely change ```mCardWidget.postalCodeRequired = false``` when ```postalCodeEnabled={false}```
For some reason, react props are applied to Android native element in unexpected order (countryCode first, then postalCodeEnabled), which in conjunction with default value of ```polstalCodeEnabled === true``` leads to non-working ```CardField``` on Android with ```postalCodeEnabled={false}```
Select one:
> [Issue-1146] Fix CardField validation problem on Android

- CHANGELOG.md
- android/build.gradle
- android/proguard-rules.txt
- example/android/app/build.gradle
- example/android/app/proguard-rules.pro
- example/ios/Podfile.lock
SDK now keeps `com.google.android.gms.tapandpay` and `com.stripe.android.pushProvisioning` if present. 
bug fix
Tested new rules with and without these libraries present- builds succeed even with minification
Select one:
> fix: add proguard file to keep optional push provisioning classes (if present)

- src/types/Token.ts
A PR from back in March 2022 (https://github.com/stripe/stripe-react-native/pull/863) started passing the new card ID back from the `createToken` response in native code, but it looks like the JS-land types weren't updated accordingly.
This adds it in!
Adds missing field from JS token card response type.
We use this field in our code. It's present but Typescript fails because it doesn't know it's supposed to be there.
Select one:
> fix(types): add id to token.card result type

- CHANGELOG.md
- example/ios/Podfile.lock
- example/src/screens/ApplePayScreen.tsx
- ios/Mappers.swift
- stripe-react-native.podspec
This upgrades the native iOS library to allow for the native flow to be used for Financial Connections. It also makes some minor bug fixes: 
- closes https://github.com/stripe/stripe-react-native/issues/1196
Select one: 
- [] This PR does not result in any developer-facing changes.
> [financial connections] enable native flow

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
- android/src/main/java/com/reactnativestripesdk/CardFormView.kt
removed some no-op setPadding lines, set cardMultilineWidgetContainer margins to zero
fixes https://github.com/stripe/stripe-react-native/issues/1172
before:
after:
Select one:
> fix: remove additional margin in cardform

- CHANGELOG.md
- src/components/ApplePayButton.tsx
- src/components/ApplePayButtonNative.tsx
- src/components/GooglePayButton.tsx
- src/components/GooglePayButtonNative.tsx
- src/components/PlatformPayButton.tsx
- src/types/components/ApplePayButtonComponent.ts
- src/types/components/GooglePayButtonComponent.ts
- src/types/index.ts
wraps the `requireNativeComponent` into it's own file 
fixes https://github.com/stripe/stripe-react-native/issues/1225
Select one:
> fix: unduplicate registered views

- src/hooks/useApplePay.tsx
Move NativeEventEmitter instantiation to useEffect hook as stated in [the doc](https://reactnative.dev/docs/native-modules-android#sending-events-to-javascript).
There was a warning on Android because the emitter was instantiated but never used (addListeners/remove). This PR removes the warning. 
Select one:
> fix: move NativeEventEmitter inside hook

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/GooglePayRequestHelper.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/main/res/layout/googlepay_mark_button.xml
- docs/Platform-Pay-Migration.md
- example/src/screens/ApplePayScreen.tsx
- example/src/screens/GooglePayScreen.tsx
- ios/ApplePayUtils.swift
- ios/ApplePayViewController.swift
- ios/StripeSdk.m
- ios/StripeSdk.swift
- ios/Tests/ApplePayUtilsTests.swift
- jest/mock.js
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/usePlatformPay.tsx
- src/hooks/useStripe.tsx
- src/types/PlatformPay.ts
fixes https://github.com/stripe/stripe-react-native/issues/1236
Select one:
> fix: do not double-create Stripe token in Apple Pay flow

- CHANGELOG.md
- ios/Mappers.swift
- ios/PaymentMethodFactory.swift
- ios/StripeSdk.swift
remove RCTConvert
fix https://github.com/stripe/stripe-react-native/issues/1240 and avoid other instances
Select one:
> fix: remove instances of RCTConvert

- CHANGELOG.md
- ios/ApplePayViewController.swift
closes https://github.com/stripe/stripe-react-native/issues/1261
Select one:
> fix: confirmPlatformPaySetupIntent on iOS

- CHANGELOG.md
> Release 0.23.1

- android/src/main/java/com/reactnativestripesdk/FinancialConnectionsSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayRequestHelper.kt
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/PaymentSheetAppearance.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/main/java/com/reactnativestripesdk/addresssheet/AddressLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonManager.kt
- android/src/main/java/com/reactnativestripesdk/utils/Extensions.kt
Android: use FragmentActivity instead of AppCompatActivity to improve compatibility with Flutter
As discussed in a meeting this PR will change the usage of AppCompatActivity to use its super class (FragmentAcitvity) instead. Flutter uses FragmentActivity and changing this accordingly will ease the sync with new versions.
I've been unable to run it on Android because I'm getting lots of FileNotFoundExceptions on my machine:
`java.io.FileNotFoundException: /Users/.../.gradle/caches/transforms-3/.../transformed/jetified-flipper-0.125.0/META-INF/com/android/build/gradle/aar-metadata.properties (No such file or directory)`
Select one:
> Android: use FragmentActivity instead of AppCompatActivity

- CHANGELOG.md
- android/src/androidTest/java/com/reactnativestripesdk/mappers/MappersTest.kt
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/TapAndPayProxy.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
`token` is now added regardless of the value of `canAddCard`, whereas previously it was only added to the details map if `canAddCard` was false.
In the "yellow path" on android, `canAddCard` is actually `true`
Select one:
> fix: correctly pass back token for push provisioning yellow path on android

- CHANGELOG.md
> Release 0.23.2

- CHANGELOG.md
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- example/ios/Podfile.lock
- example/yarn.lock
- package.json
- scripts/run-maestro-tests
- yarn.lock
stripe-android 20.19.2 included some breaking code changes for Kotlin, and was picked up automatically due to soft version matching. this PR fixes those
Closes https://github.com/stripe/stripe-react-native/issues/1288
Select one:
> fix: Upgrade android, fix breaking changes

- CHANGELOG.md
> Release 0.24.0 [skip actions]

- CHANGELOG.md
- ios/PaymentPassFinder.swift
- ios/PushProvisioning/AddToWalletButtonView.swift
- ios/PushProvisioning/PushProvisioningUtils.swift
- ios/StripeSdk.swift
- ios/Tests/PushProvisioningTests.swift
- src/types/PushProvisioning.ts
There is some unexpected behavior from Apple we need to account for.
1. Calling [canAddPasses](https://developer.apple.com/documentation/passkit/pkaddpassesviewcontroller/1619212-canaddpasses) on any iPad will return `false`, even though the device **can** add payment passes, so we removed reliance on that method. 
2. There is a bug in iOS which results in the `false` response from [canAddSecureElementPass](https://developer.apple.com/documentation/passkit/pkpasslibrary/3543354-canaddsecureelementpass) when a paired Watch is still available for provisioning, so we removed reliance on that method.
Temporarily fix push provisioning flow on iPads and when there is a paired watch, until Apple fixes this in PassKit.
Testing this takes a while, TODO
Select one:
> fix: Push Provisioning issues on iOS due to Apple bugs

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/PushProvisioningProxy.kt
- src/types/PushProvisioning.ts
Fixes a null pointer access error, and also introduces the `supportsTapToPay` field for `canAddCardToWallet()`. This field defaults to true, but when set to false, it will disable the check for NFC compatibility and allow merchants to provision cards on devices without tap to pay functionality
closes https://github.com/stripe/stripe-react-native/issues/1306
Select one:
> feat: make nfc check optional on android

- ios/ApplePayViewController.swift
`onDidSetShippingMethod` & `onDidSetShippingContact` events will again send data back to the `useApplePay` hook listeners as well as by using the standard `const eventEmitter = new NativeEventEmitter(NativeModules.StripeSdk);` listeners
What happened was that the:
```swift
if let callback = self.shippingMethodUpdateJSCallback { ... }
```
Would never be set in any place other than using the `ApplePayButton` component from Stripe, meaning that if you were using the `useApplePay` hook or needed to listen to the shipping changes, it would skip and never trigger the `sendEvent` function
I needed to listen to the shipping address changes programatically because the app we use has shipping available to different countries which require different tax calculations and currencies.
Select one:
> fix: allow apple pay shipping events to emit

- CHANGELOG.md
> Release 0.25.0

- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- e2e-tests/cashapp-payment.yml
- e2e-tests/cashapp-setup.yml
- e2e-tests/paypal-setup.yml
- example/ios/Podfile.lock
- example/package.json
- example/server/index.ts
- example/src/App.tsx
- example/src/screens/CashAppScreen.tsx
- example/src/screens/HomeScreen.tsx
- example/yarn.lock
- ios/Mappers.swift
- ios/PaymentMethodFactory.swift
- ios/StripeSdk.swift
- package.json
- src/types/PaymentIntent.ts
- src/types/PaymentMethod.ts
- src/types/SetupIntent.ts
- stripe-react-native.podspec
adds cashapp and paypal payment methods to payment sheet and to the API bindings, and adds the option to pass MandateData via SDK
Select one:
> feat: add cashapp and paypal payment methods, and option to pass MandateData via SDK

- src/types/ApplePay.ts
`phoneNumber` type on `ShippingContact` for ApplePay is a `string` not a `number`
Native mappers `mapFromShippingContact` give the phone number as a `string` but TS type is a `number` which is wrong.
Select one:
> fix: phone number on ShippingContact is a string

- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- ios/Mappers.swift
- src/types/PaymentMethod.ts
Added `isThreeDSecureSupported` to the `CardResult` type.
This field uses `threeDSecureUsage` to indicate whether the card supports 3DS or not.
Native SDK has this information, but the bridge does not pass this data to the RN package.
This information can be useful to improve the user experience by indicating to the user that a validation from their bank may be required `isThreeDSecureSupported` is `true`.
Select one:
> feat: add isThreeDSecureSupported on CardResult type

- CHANGELOG.md
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- example/ios/Podfile.lock
- ios/StripeSdk+PaymentSheet.swift
- src/types/PaymentSheet.ts
- stripe-react-native.podspec
allow merchants to set how they'd like to collect billing details in payment sheet
closes https://github.com/stripe/stripe-react-native/issues/1034
Select one:
> feat: add billingDetailsCollectionConfiguration to payment sheet

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
match TS types
fixes https://github.com/stripe/stripe-react-native/issues/1365
- [] I added automated tests
Select one:
> fix: created should be string on android

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
we weren't taking out the `googlePay` object before
closes https://github.com/stripe/stripe-react-native/issues/1371
Select one:
> fix: existingPaymentMethodRequired on android's isPlatformPaySupported

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonView.kt
`createUrlFromSourceMap` is now `getUrlOrResourceId` and will get the GlideUrl if the uri is a valid url, otherwise it will assume we're running in release mode and react-native has given us a resource string from `resolveAssetSource`
AddToWalletButton wouldn't show up in release on android if you used `Image.resolveAssetSource`
Select one:
> fix: resolve resource ID for AddToWalletButton in release mode

- ios/StripeSdk.swift
cast as NSError so we can pull more details from the error object
closes https://github.com/stripe/stripe-react-native/issues/1344
> fix: Resolve with better errors on iOS

- android/src/main/java/com/reactnativestripesdk/FinancialConnectionsSheetFragment.kt
unpacks these map entries manually rather than casting to avoid a cast error
fixes https://github.com/stripe/stripe-react-native/issues/1400
> fix: unpack map entries manually

- src/components/PlatformPayButton.tsx
- src/types/PlatformPay.ts
onShippingContactSelected only gets fired when PlatformPay.ContactField.PostalAddress is included in requiredShippingAddressFields. I believe this is due to apple's [redaction behavior](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypayment/1916097-shippingcontact), but there is no confirmation of that in the official [PKPaymentAuthorizationViewController docs](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/2865761-paymentauthorizationviewcontroll)
> fix: better docs for requiredShippingAddressFields

- CHANGELOG.md
- src/functions.ts
Only calls native method if we're on iOS
This only applies to iOS
> fix: handle url callback android

- CHANGELOG.md
> Stripe React Native Release v0.29.0

- CHANGELOG.md
Linking to the subheadings isn't super useful + they aren't evergreen
> [skip actions] remove subsection headings in changelog, use bold instead

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/pushprovisioning/TapAndPayProxy.kt
- src/types/PushProvisioning.ts
fixes https://github.com/stripe/stripe-react-native/issues/1453
`canAddCardToWallet` now returns the `fpanLastFour` and `dpanLastFour` in the `GooglePayCardToken` type. The `cardLastFour` field (which is now superseded by `fpanLastFour`) is deprecated.
> fix: return both last four types from google tokenized cards

- CHANGELOG.md
- example/src/screens/PaymentsUICompleteScreen.tsx
- ios/StripeSdk+PaymentSheet.swift
- src/types/PaymentSheet.ts
Optional configuration to display a custom message when a saved payment method is removed. iOS only.
Select one:
> [ios] add support for removeSavedPaymentMethodMessage for payment sheet

- CHANGELOG.md
- ios/ApplePayViewController.swift
- ios/StripeSdk.swift
This is `null` from stripe-ios, so we need to intercept the value earlier and save it, then set the key/value pair manually before resolving the promise
fixes https://github.com/stripe/stripe-react-native/issues/1499
Select one:
> fix: include payment method in return from confirmPlatformPayPayment/confirmPlatformPaySetupIntent

- CHANGELOG.md
- ios/AddressSheet/AddressSheetView.swift
- ios/CustomerSheet/CustomerSheetUtils.swift
- src/components/AddressSheet.tsx
- src/types/CustomerSheet.ts
adds the rest of the enum values
fixes https://github.com/stripe/stripe-react-native/issues/1514
Select one:
> feat: add new presentationStyle options

- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
Get `phoneNumber` from `shippingInformation` to avoid null value if required
Select one: 
fixes: https://github.com/stripe/stripe-react-native/issues/1518
> fix: phone number is in shippingInformation

- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
Handle case where `line2` is null to not display `null` during the concatenation.
There are many cases to do this in Kotlin, let me know if you prefer something else ;)
I want to get a street address with the right formatting.
Select one: 
fixes: https://github.com/stripe/stripe-react-native/issues/1520
> fix: prevent null in street name

- android/src/main/java/com/reactnativestripesdk/GooglePayLauncherFragment.kt
- src/types/PlatformPay.ts
For some reason React Native crashes when calling `getInt` if the key doesn't exist (but not when calling `get` on the rest of the types)
fixes https://github.com/stripe/stripe-react-native/issues/1436#issuecomment-1740487382
Select one:
> Fix crash when starting up Google Pay

- CHANGELOG.md
- android/build.gradle
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- e2e-tests/paymentsheet-customFlow-decoupled.yml
- e2e-tests/paymentsheet-customFlow.yml
- e2e-tests/paymentsheet-decoupled.yml
- example/ios/Podfile.lock
- stripe-react-native.podspec
Upgrade to 20.34.+ on android, 23.18.+ on iOS
> chore: upgrade dependencies

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- example/ios/Podfile.lock
- example/server/index.ts
- example/src/App.tsx
- example/src/screens/HomeScreen.tsx
- example/src/screens/RevolutPayScreen.tsx
- ios/Mappers.swift
- ios/PaymentMethodFactory.swift
- src/types/PaymentIntent.ts
adds revolut pay as a payment method through bindings. this is already available in the payment element
https://jira.corp.stripe.com/browse/RUN_DX-2311
Select one:
> feat: add revolut pay pm

- android/src/main/java/com/reactnativestripesdk/CardFormView.kt
After upgrading to React Native 0.73, the following Android build error is thrown:
```
Task :stripe_stripe-react-native:compileDebugKotlin FAILED
e: ~/mobile/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/CardFormView.kt:31:70 Unresolved reference: style
```
Fixes https://github.com/stripe/stripe-react-native/issues/1578
I don't believe automated testing is necessary for this. Please advise. 
No documentation needed
Select one:
> fix: RN 0.73 Build error  #1578

- jest/mock.js
change `useStripe` mock to return functions rather than other hooks
My unit test failed on the mock provided from this repo.
In reality `useStripe` doesn't return 100% all functions listed in the `mockFunctions` object, but using a superset for the mock should still be fine as TS won't allow calling the functions which are not in the declared in the return value type of `useStripe`. Returning hooks definitely is not what happens in `useStripe`.
No need for automated tests
> test: fix mock for useStripe

- android/src/main/java/com/reactnativestripesdk/CardFieldView.kt
- android/src/main/java/com/reactnativestripesdk/CardFormView.kt
- android/src/main/java/com/reactnativestripesdk/GooglePayButtonView.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
Solved Lint problems (related to issue #1430) that make lint analysis fail and not completing the build, applying the proposed solution. Solved an additional problem with lint error "Identity equality for arguments of types Boolean and Boolean is deprecated".
I am making the change because I faced those problems in my react-native project, and I solved them applying the proposed changes. I need to apply them manually if I install something new and I prefer not to doing it manually every time.
Select one:
> fix: Solved Lint problems (related to issue #1430) and additional problem related with Boolean comparison.

- example/ios/Podfile.lock
- ios/CardFormView.swift
before we were setting this _before_ CardForm was initialized. now we call it after
closes https://github.com/stripe/stripe-react-native/issues/1627
Select one:
> fix: setting preferred networks on cardform

- CHANGELOG.md
- android/gradle.properties
updated stripe-android from 20.44.+ to 20.47.3
> chore: update android dependency to 20.47.3

- CHANGELOG.md
- android/gradle.properties
- example/ios/Podfile.lock
- stripe-react-native.podspec
- Updated `stripe-ios` to 23.28.\*
- Updated `stripe-android` to 20.48.\*
> chore: upgrade native libraries

- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
In the `confirmHandler`, you are supposed to be able to use the `intentCreationCallback` to either show an error or continue the flow by providing a `clientSecret`. However, on Android, after the first time you call `intentCreationCallback`, the payment sheet seems to be "stuck" on that error and doesn't allow you to update the error to a different one or take the success flow. It's caused because we never reset the completable internally, so it gets completed the first time the callback is called and then every subsequent time it is referenced it just gives that first value it was completed with.
You can see a repro for this
1. `git clone https://github.com/miduncan/stripe-react-native-fix.git`
2. `git checkout miduncan-repro`
3. start the android project and use the "Accept a Payment -> …
> fix: allow intentCreationCallback to use the latest callback value in Android

- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/customersheet/CustomerSheetFragment.kt
`getBoolean` defaults to false if the key isn't present, but we need it to default to true
> fix: make allowsRemovalOfLastSavedPaymentMethod default to true on android

- CHANGELOG.md
> Release v0.38.4

- CODEOWNERS
Add the iOS and Android teams as approved reviewers
Allows us to enable the CODEOWNERS requirement without @charliecruzan-stripe having to review every patch
GitHub's built-in linter
Select one:
> Add iOS and Android teams to CODEOWNERS

- CHANGELOG.md
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/customersheet/CustomerSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/customersheet/ReactNativeCustomerAdapter.kt
- example/ios/Podfile.lock
- example/package.json
- example/server/index.ts
- example/src/components/CustomerSessionSwitch.tsx
- example/src/helpers.ts
- example/src/screens/PaymentSheetDeferredIntentMultiStepScreen.tsx
- example/src/screens/PaymentSheetDeferredIntentScreen.tsx
- example/src/screens/PaymentSheetWithSetupIntent.tsx
- example/src/screens/PaymentsUICompleteScreen.tsx
- example/src/screens/PaymentsUICustomScreen.tsx
- example/yarn.lock
- ios/StripeSdk+PaymentSheet.swift
- src/types/PaymentSheet.ts
- stripe-react-native.podspec
Add logic to parse `customerSessionClientSecret`
Support Customer Session for React Native
[MOBILESDK-2432](https://jira.corp.stripe.com/browse/MOBILESDK-2432)
[MOBILESDK-2431](https://jira.corp.stripe.com/browse/MOBILESDK-2431)
Select one:
> Parse 'customerSheetClientSecret' for Android and iOS

- CHANGELOG.md
- example/src/screens/CustomerSheetScreen.tsx
- src/components/CustomerSheet.tsx
This is now GA'd on both ios and android, so let's GA for RN as well
> feat: GA customer sheet

- CHANGELOG.md
> Release v0.40.0

- CHANGELOG.md
- example/ios/Podfile.lock
- stripe-react-native.podspec
wysiwyg
matches https://github.com/stripe/stripe-identity-react-native/pull/176
> chore: upgrade stripe ios to 24.1

- ios/StripeSdk.swift
The problem here is that a call within the stripe-ios library to initialize a PKPaymentAuthorizationResult is passing the error that we pass in from RN, which conforms to this [class](https://stripe.sourcegraphcloud.com/stripe/stripe-react-native/-/blob/ios/StripeSdk.swift?L141-149), which is not "sendable". but PKPaymentAuthorizationResult expects that it is sendable. classes _can_ be made sendable, but we should just use a struct here
fixes https://github.com/stripe/stripe-react-native/issues/1748
Select one:
> use sendable struct instead of class

- .github/workflows/generate-docs.yml
new secrets cannot start with `GITHUB_`
> [git] update secret for docs workflow

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/CollectBankAccountLauncherFragment.kt
- android/src/main/java/com/reactnativestripesdk/FinancialConnectionsSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
- example/src/screens/ACHPaymentScreen.tsx
- example/src/screens/CollectBankAccountScreen.tsx
- ios/FinancialConnections.swift
- ios/Mappers.swift
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/hooks/useFinancialConnectionsSheet.tsx
- src/hooks/useStripe.tsx
- src/types/FinancialConnections.ts
- src/types/PaymentMethod.ts
This pull request adds support for passing an `onEvent` handler to Financial Connections methods, similar to the native Android and iOS SDKs.
[MOBILE_APIREVIEW-117](https://jira.corp.stripe.com/browse/MOBILE_APIREVIEW-117)
Select one:
> Support events in Financial Connections

- example/ios/Podfile.lock
- stripe-react-native.podspec
Bump to the latest iOS SDK version so that we can offer dark mode in the Financial Connections SDK.
Unblocks https://docs.google.com/document/d/18K0cu07lVchrDAPaPzEtaCHe2At4H_eXqd2-Op1a7a0/edit?usp=sharing
`yarn run test` still passes!
N/a
> Bump Stripe iOS SDKs to v24.7.0

- CHANGELOG.md
- example/src/screens/ACHPaymentScreen.tsx
- example/src/screens/ACHSetupScreen.tsx
- ios/FinancialConnections.swift
- ios/StripeSdk.m
- ios/StripeSdk.swift
- src/NativeStripeSdk.tsx
- src/functions.ts
- src/types/Common.ts
- src/types/FinancialConnections.ts
- src/types/PaymentMethod.ts
- src/types/PaymentSheet.ts
**API Review:** [Dark Mode in FC for React Native](https://docs.google.com/document/d/18K0cu07lVchrDAPaPzEtaCHe2At4H_eXqd2-Op1a7a0/edit?usp=sharing)
We recently [shipped](https://groups.google.com/a/stripe.com/d/msgid/connections-shipped/CAHNjHvyduE%3Dwv_UP52PmqV_jT%3DYJ7muT4S-jmXs0nc1EP7qGkQ%40mail.gmail.com) Dark Mode in the native mobile Financial Connections SDKs. This introduced a [new public API](https://docs.google.com/document/d/1pjaQA4LM3NVjC2PFr7_rgGleymHHbE_RTudNEgih5jw/edit?usp=sharing) for configuring the theme, such as specifying always light or always dark mode. We’d like to offer a similar API in our React Native SDK such that our React Native users can make use of this feature.
We’re adding an optional style property to the following models:
- `CollectBankAccountParams`
- …
> Dark mode support in FC: Add style param to Bank Account Collector API

- example/package.json
When starting the server the first time in the example app it crashes, because the code hasn't been compiled yet.
This builds the server in postinstall script to make sure the code exists when running the start:server script.
Avoids crashing the first time the server is launched.
Select one:
> Fix example start server on first launch

- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
Upgrade Stripe Android SDK to 21.6.0
Allows access to new Android APIs developed since `20.52.+`
Select one:
> Upgrade Stripe Android SDK to 21.6.0

- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/customersheet/CustomerSheetFragment.kt
- android/src/main/java/com/reactnativestripesdk/utils/KeepJsAwakeTask.kt
- src/components/CustomerSheet.tsx
- src/components/StripeProvider.tsx
I noticed that the customer sheet loads indefinitely when using a `customerAdapter` when the new arch is enabled.
To reproduce in the example app:
Set `newArchEnabled=true` and `bridgelessEnabled=true` in gradle.properties.
Then go to:
Accept a Payment -> Customer Sheet -> Select Use Component -> Edit Payment Methods
This happens because on the new arch with bridgeless enabled, a web like event loop is implemented and used in the fetch implementation. This event loop requires timers to be running to work, but when an activity is paused react native pauses timers. This causes fetch to hang until the customer sheet is closed, so the sheet never loads when using a custom customer adapter.
The best way I found to fix this is to trick react native into not pausing timers by creating a headless …
> Fix JS running during presented UI on new arch Android

- example/src/screens/PaymentsUICompleteScreen.tsx
- ios/CustomerSheet/CustomerSheetUtils.swift
- ios/StripeSdk+CustomerSheet.swift
- ios/StripeSdk+PaymentSheet.swift
- src/types/CustomerSheet.ts
- src/types/PaymentSheet.ts
Users will use this flag to opt-into update payment method if they've integrated with customerSessions
UpdatePaymentSheet private beta
Select one:
> Parse string for updatePaymentMethod when using customerSessions on iOS

- example/src/screens/PaymentsUICompleteScreen.tsx
- ios/CustomerSheet/CustomerSheetUtils.swift
- ios/StripeSdk+CustomerSheet.swift
- ios/StripeSdk+PaymentSheet.swift
- src/types/CustomerSheet.ts
- src/types/PaymentSheet.ts
This reverts commit fb7a6305c5cd98028655414181dfdba978575550.
No longer needed as we no longer have a client side flag
This is no longer needed.
Select one:
> Revert "Parse string for updatePaymentMethod when using customerSessions on iOS (#1880)"

- .github/workflows/e2e-tests.yml
- .gitignore
- scripts/run-maestro-tests
I had some issues debugging e2e ci since artifacts were not available for some reason, this config fixes it.
Make e2e test failures easier to debug.
Select one:
> Fix CI e2e test artifacts upload

- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementView.kt
- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementViewManager.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/oldarch/java/com/facebook/react/viewmanagers/EmbeddedPaymentElementViewManagerDelegate.java
- android/src/oldarch/java/com/facebook/react/viewmanagers/EmbeddedPaymentElementViewManagerInterface.java
- src/specs/NativeEmbeddedPaymentElement.ts
- src/types/EmbeddedPaymentElement.tsx
Fix Android `Embedded` calls to native functions
While working on the height solution for Embedded RN, I noticed that the calls to `confirm` and `clearPaymentOption` did not execute. This PR fixes that so the calls go through.
Select one:
> Fix Android `Embedded` calls to native functions

- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementView.kt
- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementViewManager.kt
- android/src/main/java/com/reactnativestripesdk/StripeAbstractComposeView.kt
- e2e-tests/android-only/embedded-rnscreens.yml
- example/src/screens/EmbeddedPaymentElementScreen.tsx
This fixes an issue with screens and compose. The issue is described here https://github.com/software-mansion/react-native-screens/issues/2098. Basically if a screen is pushed on top of a view using compose when the screen is dismissed the compose view will disappear.
We can reproduce this issue with our Embedded component in the example app with the "Push screen" button added in this PR. Tap on the button then go back and the Embedded view is no longer visible.
What happens is that react native screens reuses views when a fragment is destroyed, which composes doesn't support by default. So when pushing a new screen the previous screen fragment is destroyed causes the compose view to be disposed. When the fragment is re-created when going back, the disposed compose view is re-used which …
> Fix compose views inside react-native-screens fragments

- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementView.kt
- android/src/main/java/com/reactnativestripesdk/utils/KeepJsAwakeTask.kt
This adds a KeepJsAwakeTask call to make sure JS can execute while Embedded Card sheet is presented. This is needed on new arch.
Fix Embedded on Android with new arch.
Select one:
> Fix embedded on Android new arch

- android/build.gradle
- android/src/main/java/com/reactnativestripesdk/EmbeddedPaymentElementView.kt
- src/types/EmbeddedPaymentElement.tsx
Support dynamic height for Embedded on Android.
Ensure `Embedded` reacts properly for height changes on Android for React Native.
Select one:
> Support dynamic height for Embedded on Android

- android/src/main/java/com/reactnativestripesdk/StripeAbstractComposeView.kt
- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- e2e-tests/android-only/embedded-rn-compose.yml
- example/src/screens/EmbeddedPaymentElementScreen.tsx
Android Dialog class, which react-native modal uses doesn't propagate the context that compose needs to work. Usually the context would be created, but because react-native tries to measure the compose view before it is attached to the window it crashes.
To avoid this we can create the context compose needs (by creating a dummy compose view) when initializing the stripe sdk and attaching the context from that view on our compose views.
Allow using compose views inside of modals.
Select one:
> Fix compose views inside react-native Modal

- scripts/publish
We've had issues with the deploy script. The yarn commands pass the -s flag for silent, but this swallows all error output which makes debugging failures very hard. For example if a tag already exists the script would just exit before with no output. This also fixes the `hub` check, before it would exit the script since we're using these `set -euo pipefail` bash flags if hub is not installed.
Make deploy failures easier to debug.
Select one:
> Deploy script fixes

- scripts/run-maestro-tests
Currently the artifacts generated by e2e tests are hard to analyze. Each test generate a folder with a data so to find the failing test you basically need to open every folder. This changes the structure so we create a folder with the name of the test, and optionally the retry.
Before:
After:
Make debugging e2e test failures easier.
Select one:
> Improve e2e tests artifacts

- ios/NewArch/GooglePayButtonComponentView.mm
On older version of react-native every single spec is linked so we need to add this dummy implementation for GooglePayButton. On more recent versions this was not a problem since we provide an explicit list of views to link.
Fixes compatibility with 0.76 new arch.
Fixes #1923
Select one:
> Fix iOS build on react-native 0.76 new arch

- android/src/oldarch/java/com/facebook/react/viewmanagers/AddToWalletButtonManagerInterface.java
- android/src/oldarch/java/com/facebook/react/viewmanagers/AddressSheetViewManagerInterface.java
- android/src/oldarch/java/com/facebook/react/viewmanagers/ApplePayButtonManagerInterface.java
- android/src/oldarch/java/com/facebook/react/viewmanagers/AuBECSDebitFormManagerInterface.java
- android/src/oldarch/java/com/facebook/react/viewmanagers/CardFieldManagerInterface.java
- android/src/oldarch/java/com/facebook/react/viewmanagers/CardFormManagerInterface.java
- android/src/oldarch/java/com/facebook/react/viewmanagers/EmbeddedPaymentElementViewManagerInterface.java
- android/src/oldarch/java/com/facebook/react/viewmanagers/GooglePayButtonManagerInterface.java
- android/src/oldarch/java/com/facebook/react/viewmanagers/StripeContainerManagerInterface.java
- scripts/old-arch-codegen-android
In older version of react native this `ViewManagerWithGeneratedInterface` interface does not exist. It is not needed for old arch so we should remove it.
Fix backwards compatibility with RN 0.77.
Fixes #1919
Select one:
> Remove ViewManagerWithGeneratedInterface from old arch interfaces

- .github/workflows/e2e-tests.yml
- e2e-tests/rn-arch.yml
- example/android/gradle.properties
- example/ios/Podfile
- example/ios/Podfile.lock
- example/src/screens/HomeScreen.tsx
- scripts/run-maestro-tests
Run e2e test on both old arch and new arch.
This also switches the example app to new arch by default.
Improve test coverage of new arch.
Select one:
> Run e2e CI on both new and old arch

- src/types/EmbeddedPaymentElement.tsx
- Adds customer secret keys to the embedded APIs
- These are already being parsed by native code, just an oversight initially
- Complete the API
Select one:
> Add customer secrets to embedded API

- CHANGELOG.md
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentSheetAppearance.kt
- example/ios/Podfile.lock
- ios/PaymentSheetAppearance.swift
- src/types/PaymentSheet.ts
- stripe-react-native.podspec
Add `formInsetValues` and `PrimaryButtonConfig.shapes.height` to `AppearanceParams`
Update `stripe-ios` to version `24.15.0`
Update `stripe-android` to version `21.17.+`
https://jira.corp.stripe.com/browse/MOBILESDK-3610
Select one:
> Add Form Insets and Primary Button height API

- e2e-tests/android-only/financial-connections-session.yml
- e2e-tests/android-only/financial-connections-token.yml
Tests were failing because the financial connections manual bank account info entry page has new button text for filling in test account details.
CI is better when it's not broken.
Select one:
> Update tests to reflect new web page button text

- ios/StripeSdkImpl.swift
Provides dashboard functionality for setting live/test mode.
```
useEffect(() => {
Settings.set({'stripe_userKeyLiveMode': liveMode})
initStripe({
publishableKey: apiKey 
stripeAccountId: accountId,
urlScheme: scheme,
});
}, [apiKey, liveMode, accountId, scheme]);
```
> Add functionality to set userKeyLiveMode value for user keys.

- .github/workflows/e2e-tests.yml
Added a scheduled midnight PT E2E test run.
Also added a job to the work flow that sends an email to the run slack channel. Currently testing that this sends an email to the slack channel as intended.
https://jira.corp.stripe.com/browse/RUN_MOBILESDK-4464
Incident remediation for violet lonely
I need to test that this works on github
Select one:
> Nightly e2e tests

- CHANGELOG.md
> Propose 0.50.1

- CLAUDE.md
- example/src/screens/ApplePayScreen.tsx
- ios/StripeSdkImpl.swift
When `const { paymentIntent, error } = await confirmPlatformPayPayment()` is called twice in quick succession (e.g. if the user double taps the button), we'll fail with a "user cancelled" error. This is confusing, so let's instead return a more explicit error.
We'll also adjust the example code so that it tracks whether Apple Pay is in-flight.
https://github.com/stripe/stripe-react-native/issues/1970
Select one:
> Protect against accidental Apple Pay button clicks

- example/src/screens/EmbeddedPaymentElementScreen.tsx
- Lay the embedded view out in the safe area to prevent it from being smushed.
- Fix modal crash on second open. The root cause of the issue was multiple concurrent EmbeddedPaymentElement instances causing conflicts in the native layer, which was resolved by implementing conditional rendering to ensure only one PaymentElementView exists at a time.
> Handle safe area in embedded app and fix crash

- CHANGELOG.md
- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentSheetAppearance.kt
- example/ios/Podfile.lock
- example/src/screens/EmbeddedPaymentElementImmediateActionScreen.tsx
- ios/PaymentSheetAppearance.swift
- src/types/PaymentSheet.ts
- stripe-react-native.podspec
- Renamed `RowStyle.FlatWithChevron` to `RowStyle.FlatWithDisclosure` and updated related interfaces (`ChevronConfig` → `DisclosureConfig`).
- Updated `stripe-ios` to 24.19.0
- Updated `stripe-android` to 21.22.+
- Bug fixes
- Manual
- CI
> Bump native libs, rename FlatWithChevron

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentSheetAppearance.kt
- example/src/screens/EmbeddedPaymentElementScreen.tsx
- ios/PaymentSheetAppearance.swift
- src/types/PaymentSheet.ts
- Added `successBackgroundColor` and `successTextColor` properties to `PrimaryButtonColorConfig` for customizing the primary button appearance in success states.
- Parity with native
Manual
> Add success colors to primary button config

- jest/mock.js
Adds in missing mocks for the EmbeddedPaymentElement and various other APIs.
Resolves https://github.com/stripe/stripe-react-native/issues/2046
> Update mocks.js with new APIs

- android/gradle.properties
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
This is step 1 to enable merchants to use the new callback in RN as well.
> Update to the latest Android SDK, and adopt the new PaymentOptionResultCallback.

- .github/workflows/e2e-tests.yml
- .github/workflows/js-tests.yml
- .github/workflows/unit-tests.yml
- This step was causing CI jobs to be errnounysly canceled
> Remove cancel stuff from CI workflows

- package.json
- yarn.lock
Some users have been getting a INVALID_PLUGIN_IMPORT error when building on expo, the error also happens when using the expo vscode extension.
Fixes #1915
This also updates the version of `react-native-builder-bob` as I wanted to see if the latest version also creates those package.json files, but it does. I kept the version upgrade, but can revert if you prefer as it doesn't fix the issue.
`react-native-builder-bob` generates package.json files under the lib folder, which seems to confuse how expo resolves the config plugin. I went looking at other libraries that have an expo plugin and build using bob and found this https://github.com/zoontek/react-native-bootsplash/blob/master/package.json#L50. 
Select one:
> Fix config plugin INVALID_PLUGIN_IMPORT error

- android/gradle.properties
- example/ios/Podfile.lock
- stripe-react-native.podspec
Bumps native SDKs to their latest versions:
- Android 21.26.0
- iOS: 24.23.1
Select one:
> [Onramp] Bumps native versions

- android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt
- android/src/oldarch/java/com/reactnativestripesdk/NativeStripeSdkModuleSpec.java
- e2e-tests/ios-only/financial-connections-session.yml
- e2e-tests/ios-only/financial-connections-token.yml
- example/src/screens/CollectBankAccountScreen.tsx
- ios/StripeSdk.mm
- ios/StripeSdkImpl.swift
- src/functions.ts
- src/specs/NativeStripeSdkModule.ts
This pull request [re-enables](https://github.com/stripe/stripe-react-native/pull/1963) the Financial Connections tests on iOS by forcing the native flow for the test merchant.
We use the native flow instead of the web flow to reduce flakiness. Both flows are transparent to the caller; the main purpose of these tests is to confirm that the interface between React Native and Swift code works as intended. Proper end-to-end tests of the Financial Connections SDK exist in the native repos.
Select one:
> Re-enable FC tests on iOS by forcing native flow

- android/src/main/java/com/reactnativestripesdk/utils/KeepJsAwakeTask.kt
A user wrote in suggesting a fix for this, it doesn't seem harmful, so I'm adding it in.
https://jira.corp.stripe.com/browse/RUN_MOBILESDK-4693
> Fix a potential bug in the stop method.

- CHANGELOG.md
- android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
- Fixes an issue where we were not handling images with alpha correctly in React Native
> Fix handling images with alpha in embedded android

- CHANGELOG.md
> 0.54.0 propose

- CHANGELOG.md
> 0.54.1 proposal
